In [1]:
import os
import pandas as pd

In [2]:
# Change the working directory

os.chdir(r"C:\Users\Clinton Ombiro\Desktop\Python Datasets")

In [3]:
# Load in the DataFrame

df = pd.read_csv(r"C:\Users\Clinton Ombiro\Desktop\Python Datasets\glassdoor_jobs.csv")

In [4]:
# Read the DataFrame

df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Make a copy of the DataFrame and read it

In [5]:
df_modified = df.copy()

In [6]:
df_modified

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Check the available columns

In [7]:
df_modified.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

# Cleaning the Data

##### Remove all -1s in the DataFrame

In [8]:
# Salary parsing
# Remove all -1's
df_modified = df_modified[df_modified["Salary Estimate"]!='-1']

In [9]:
df_modified

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Remove (Glassdoor est.) from the Salary Estimate column

In [10]:
#df_modified["Salary Estimate"] = [x.split("(")[0] for x in df_modified["Salary Estimate"]]
df_modified["Salary Estimate"]= df_modified["Salary Estimate"].apply(lambda x: x.split("(")[0])

<ipython-input-10-5df964406e04>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Salary Estimate"]= df_modified["Salary Estimate"].apply(lambda x: x.split("(")[0])

In [11]:
df_modified

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,$72K-$133K,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,$61K-$126K,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Remove all 'K' characters and dollar sign in the Salary Estimate column

In [12]:
#df_modified["Salary Estimate"]= [x.replace("K", '').replace("$", '') for x in df_modified["Salary Estimate"]]
df_modified["Salary Estimate"] = df_modified["Salary Estimate"].apply(lambda x: x.replace("K", '').replace("$", ""))

<ipython-input-12-608f4d658cfd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Salary Estimate"] = df_modified["Salary Estimate"].apply(lambda x: x.replace("K", '').replace("$", ""))

In [13]:
df_modified

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Check the Salary Estimate data type

In [14]:
df_modified["Salary Estimate"].dtypes

dtype('O')

In [15]:
df_modified.tail(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
875,875,Clinical Laboratory Scientist,24-39 Per Hour,POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health\n3.7,"Vail, CO","Vail, CO",501 to 1000 employees,1966,Hospital,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1
877,877,"Data Analyst 1, full-time contract worker for ...",35-65,"Purposes\n\nIn addition to your application, p...",4.2,The Church of Jesus Christ of Latter-day Saint...,"Salt Lake City, UT","Salt Lake City, UT",10000+ employees,-1,Nonprofit Organization,Religious Organizations,Non-Profit,Unknown / Non-Applicable,-1
878,878,Data Scientist,77-132,"Crossix is seeking intellectually curious, res...",3.5,Crossix Solutions\n3.5,"New York, NY","New York, NY",201 to 500 employees,2005,Company - Public,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
879,879,Data Scientist,51-88,Job Description Header 2 Data scientist Locati...,4.3,Solugenix Corporation\n4.3,"Phoenix, AZ","Brea, CA",201 to 500 employees,1969,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1
880,880,Data Scientist,101-141,American Career College and West Coast Univers...,2.6,West Coast University\n2.6,"Irvine, CA","Irvine, CA",10000+ employees,1997,Company - Private,Colleges & Universities,Education,Unknown / Non-Applicable,-1
881,881,Data Engineer - Consultant (Charlotte Based),59-112,Do YOU love working with Data in machine learn...,4.2,Clarity Insights\n4.2,"Charlotte, NC","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1
883,883,Data Engineer,79-147,WHO WE ARE\n\nNCSOFT® established in 1997 and ...,3.1,NCSOFT\n3.1,"Aliso Viejo, CA","Seoul, South Korea",1001 to 5000 employees,1997,Company - Public,Video Games,Media,$10+ billion (USD),"Blizzard Entertainment, Riot Games, Electronic..."
884,884,Data Scientist (Warehouse Automation),79-127,"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics\n3.8,"San Francisco, CA","Paris, France",201 to 500 employees,2005,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1
886,886,"Scientist, Immuno-Oncology",62-119,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
887,887,Senior Data Scientist,119-187,At Factual we love all things data! Our missio...,4.3,Factual\n4.3,"Los Angeles, CA","Los Angeles, CA",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,Foursquare
892,892,Jr. Data Scientist,81-132,MITRE\nis a trusted operator of federally fund...,3.2,MITRE\n3.2,"McLean, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC"
893,893,Senior Data Scientist,Employer Provided Salary:120-140,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync\n5.0,"Ann Arbor, MI","Ann Arbor, MI",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
895,895,Products Data Analyst II,90-157,TriNet is a leading provider of comprehensive ...,3.3,TriNet\n3.3,"Dublin, CA","Dublin, CA",1001 to 5000 employees,1988,Company - Public,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP"
896,896,Data Architect / Data Modeler,63-110,Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions\n4.3,"New York, NY","New York, NY",1001 to 5000 employees,1999,Company - Public,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle
897,897,Analytics Manager - Data Mart,42-86,We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health\n3.5,"Scotts Valley, CA","Scotts Valley, CA",501 to 1000 employees,1996,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
898,898,Lead Data Analyst,32-62,JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost\n3.9,"New York, NY","New York, NY",201 to 500 employees,2010,Company - Private,Internet,Information Technology,$10 to $25 million (USD),-1
899,899,Data Science Engineer - Mobile,116-208,Mobile is a top strategic priority for Adobe. ...,4.0,Adobe\n4.0,"San Jose, CA","San Jose, CA",10000+ employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft"
900,900,Senior Data Scientist Oncology,107-173,At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
901,901,Data Scientist,65-113,DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC\n3.4","Olympia, WA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1
902,902,Sr. Data Engineer - Contract-to-Hire (Java),69-127,As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC\n3.0,"Knoxville, TN","Knoxville, TN",10000+ employees,1958,Company - Private,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ..."
904,904,Senior Data Scientist - R&D Oncology,102-172,"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca\n3.9,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis"
907,907,Data Engineer,74-124,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
909,909,Food Scientist - Developer,40-68,Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza\n3.3,"Milwaukee, WI","Milwaukee, WI",501 to 1000 employees,1964,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1
910,910,Senior Data Engineer,76-142,Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC\n3.2,"Franklin, TN","Indianapolis, IN",1001 to 5000 employees,2004,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1
911,911,Data Engineer,76-142,MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems\n3.4,"Rockville, MD","Reston, VA",201 to 500 employees,1999,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1
912,912,Senior Data Scientist,108-171,"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks\n4.4,"Natick, MA","Natick, MA",1001 to 5000 employees,1984,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1
913,913,"Director II, Data Science - GRM Actuarial",202-306,Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance\n3.3,"Chicago, IL","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm"
914,914,Machine Learning Engineer,91-159,We are seeking a highly-experienced ML Enginee...,3.2,Information Builders\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,1975,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica"
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",80-133,"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,21-34 Per Hour,Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1
920,920,"Scientist, Molecular/Cellular Biologist",49-97,"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,..."
921,921,Staff Scientist-Downstream Process Development,49-113,ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1
924,924,Data Scientist,96-161,SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
926,926,Scientist - Analytical Services,65-134,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
928,928,"Associate Scientist / Sr. Associate Scientist,...",59-125,"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat..."
929,929,Associate Data Analyst- Graduate Development P...,32-59,Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
930,930,Sr. Data Engineer,87-158,Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
931,931,Clinical Data Analyst,27-48,Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth"
932,932,IT Associate Data Analyst,39-69,"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
933,933,Business Data Analyst,36-71,(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com"
934,934,Senior Insurance Data Scientist,107-173,"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1
935,935,Senior Data Science Systems Engineer,56-99,"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC"
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:25-28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1
938,938,Senior Scientist - Regulatory Submissions,80-155,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
939,939,Scientist - Biomarker and Flow Cytometry,43-98,"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1
940,940,Revenue Analytics Manager,45-78,HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1
941,941,Sr. Scientist Method Development,50-110,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
942,942,"Associate Scientist, LC/MS Biologics",44-96,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:100-140,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
944,944,IT - Data Engineer II,61-119,IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn"
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences"
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

#### Create a new column called 'hourly'

In [16]:
#df_modified["hourly"] = [1 if 'per hour' in x.lower() else 0 for x in df_modified["Salary Estimate"]]
df_modified["hourly"] = df_modified["Salary Estimate"].apply(lambda x: 1 if 'per hour' in x.lower() else 0)

<ipython-input-16-4462e1f0c91b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["hourly"] = df_modified["Salary Estimate"].apply(lambda x: 1 if 'per hour' in x.lower() else 0)

In [17]:
df_modified.tail(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly
875,875,Clinical Laboratory Scientist,24-39 Per Hour,POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health\n3.7,"Vail, CO","Vail, CO",501 to 1000 employees,1966,Hospital,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1
877,877,"Data Analyst 1, full-time contract worker for ...",35-65,"Purposes\n\nIn addition to your application, p...",4.2,The Church of Jesus Christ of Latter-day Saint...,"Salt Lake City, UT","Salt Lake City, UT",10000+ employees,-1,Nonprofit Organization,Religious Organizations,Non-Profit,Unknown / Non-Applicable,-1,0
878,878,Data Scientist,77-132,"Crossix is seeking intellectually curious, res...",3.5,Crossix Solutions\n3.5,"New York, NY","New York, NY",201 to 500 employees,2005,Company - Public,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0
879,879,Data Scientist,51-88,Job Description Header 2 Data scientist Locati...,4.3,Solugenix Corporation\n4.3,"Phoenix, AZ","Brea, CA",201 to 500 employees,1969,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,0
880,880,Data Scientist,101-141,American Career College and West Coast Univers...,2.6,West Coast University\n2.6,"Irvine, CA","Irvine, CA",10000+ employees,1997,Company - Private,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0
881,881,Data Engineer - Consultant (Charlotte Based),59-112,Do YOU love working with Data in machine learn...,4.2,Clarity Insights\n4.2,"Charlotte, NC","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0
883,883,Data Engineer,79-147,WHO WE ARE\n\nNCSOFT® established in 1997 and ...,3.1,NCSOFT\n3.1,"Aliso Viejo, CA","Seoul, South Korea",1001 to 5000 employees,1997,Company - Public,Video Games,Media,$10+ billion (USD),"Blizzard Entertainment, Riot Games, Electronic...",0
884,884,Data Scientist (Warehouse Automation),79-127,"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics\n3.8,"San Francisco, CA","Paris, France",201 to 500 employees,2005,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1,0
886,886,"Scientist, Immuno-Oncology",62-119,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0
887,887,Senior Data Scientist,119-187,At Factual we love all things data! Our missio...,4.3,Factual\n4.3,"Los Angeles, CA","Los Angeles, CA",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,Foursquare,0
892,892,Jr. Data Scientist,81-132,MITRE\nis a trusted operator of federally fund...,3.2,MITRE\n3.2,"McLean, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0
893,893,Senior Data Scientist,Employer Provided Salary:120-140,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync\n5.0,"Ann Arbor, MI","Ann Arbor, MI",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0
895,895,Products Data Analyst II,90-157,TriNet is a leading provider of comprehensive ...,3.3,TriNet\n3.3,"Dublin, CA","Dublin, CA",1001 to 5000 employees,1988,Company - Public,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP",0
896,896,Data Architect / Data Modeler,63-110,Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions\n4.3,"New York, NY","New York, NY",1001 to 5000 employees,1999,Company - Public,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle,0
897,897,Analytics Manager - Data Mart,42-86,We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health\n3.5,"Scotts Valley, CA","Scotts Valley, CA",501 to 1000 employees,1996,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0
898,898,Lead Data Analyst,32-62,JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost\n3.9,"New York, NY","New York, NY",201 to 500 employees,2010,Company - Private,Internet,Information Technology,$10 to $25 million (USD),-1,0
899,899,Data Science Engineer - Mobile,116-208,Mobile is a top strategic priority for Adobe. ...,4.0,Adobe\n4.0,"San Jose, CA","San Jose, CA",10000+ employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft",0
900,900,Senior Data Scientist Oncology,107-173,At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0
901,901,Data Scientist,65-113,DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC\n3.4","Olympia, WA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,0
902,902,Sr. Data Engineer - Contract-to-Hire (Java),69-127,As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC\n3.0,"Knoxville, TN","Knoxville, TN",10000+ employees,1958,Company - Private,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ...",0
904,904,Senior Data Scientist - R&D Oncology,102-172,"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca\n3.9,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0
907,907,Data Engineer,74-124,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0
909,909,Food Scientist - Developer,40-68,Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza\n3.3,"Milwaukee, WI","Milwaukee, WI",501 to 1000 employees,1964,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1,0
910,910,Senior Data Engineer,76-142,Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC\n3.2,"Franklin, TN","Indianapolis, IN",1001 to 5000 employees,2004,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,0
911,911,Data Engineer,76-142,MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems\n3.4,"Rockville, MD","Reston, VA",201 to 500 employees,1999,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,0
912,912,Senior Data Scientist,108-171,"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks\n4.4,"Natick, MA","Natick, MA",1001 to 5000 employees,1984,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1,0
913,913,"Director II, Data Science - GRM Actuarial",202-306,Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance\n3.3,"Chicago, IL","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0
914,914,Machine Learning Engineer,91-159,We are seeking a highly-experienced ML Enginee...,3.2,Information Builders\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,1975,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica",0
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",80-133,"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,21-34 Per Hour,Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1
920,920,"Scientist, Molecular/Cellular Biologist",49-97,"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,...",0
921,921,Staff Scientist-Downstream Process Development,49-113,ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1,0
924,924,Data Scientist,96-161,SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0
926,926,Scientist - Analytical Services,65-134,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0
928,928,"Associate Scientist / Sr. Associate Scientist,...",59-125,"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat...",0
929,929,Associate Data Analyst- Graduate Development P...,32-59,Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0
930,930,Sr. Data Engineer,87-158,Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0
931,931,Clinical Data Analyst,27-48,Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth",0
932,932,IT Associate Data Analyst,39-69,"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0
933,933,Business Data Analyst,36-71,(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",0
934,934,Senior Insurance Data Scientist,107-173,"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1,0
935,935,Senior Data Science Systems Engineer,56-99,"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:25-28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1,1
938,938,Senior Scientist - Regulatory Submissions,80-155,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0
939,939,Scientist - Biomarker and Flow Cytometry,43-98,"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1,0
940,940,Revenue Analytics Manager,45-78,HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1,0
941,941,Sr. Scientist Method Development,50-110,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0
942,942,"Associate Scientist, LC/MS Biologics",44-96,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:100-140,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,0
944,944,IT - Data Engineer II,61-119,IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1,0
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,0
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0

#### Create a new column called 'employer provided' from Salary Estimate

In [18]:
#df_modified["employer provided"] = [1 if 'employer provided salary:' in x.lower() else 0 for x in df_modified["Salary Estimate"]]
df_modified["employer provided"] = df["Salary Estimate"].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)

<ipython-input-18-5dcba6795913>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["employer provided"] = df["Salary Estimate"].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)

In [19]:
df_modified.tail(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided
875,875,Clinical Laboratory Scientist,24-39 Per Hour,POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health\n3.7,"Vail, CO","Vail, CO",501 to 1000 employees,1966,Hospital,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
877,877,"Data Analyst 1, full-time contract worker for ...",35-65,"Purposes\n\nIn addition to your application, p...",4.2,The Church of Jesus Christ of Latter-day Saint...,"Salt Lake City, UT","Salt Lake City, UT",10000+ employees,-1,Nonprofit Organization,Religious Organizations,Non-Profit,Unknown / Non-Applicable,-1,0,0
878,878,Data Scientist,77-132,"Crossix is seeking intellectually curious, res...",3.5,Crossix Solutions\n3.5,"New York, NY","New York, NY",201 to 500 employees,2005,Company - Public,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0
879,879,Data Scientist,51-88,Job Description Header 2 Data scientist Locati...,4.3,Solugenix Corporation\n4.3,"Phoenix, AZ","Brea, CA",201 to 500 employees,1969,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,0,0
880,880,Data Scientist,101-141,American Career College and West Coast Univers...,2.6,West Coast University\n2.6,"Irvine, CA","Irvine, CA",10000+ employees,1997,Company - Private,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0
881,881,Data Engineer - Consultant (Charlotte Based),59-112,Do YOU love working with Data in machine learn...,4.2,Clarity Insights\n4.2,"Charlotte, NC","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0
883,883,Data Engineer,79-147,WHO WE ARE\n\nNCSOFT® established in 1997 and ...,3.1,NCSOFT\n3.1,"Aliso Viejo, CA","Seoul, South Korea",1001 to 5000 employees,1997,Company - Public,Video Games,Media,$10+ billion (USD),"Blizzard Entertainment, Riot Games, Electronic...",0,0
884,884,Data Scientist (Warehouse Automation),79-127,"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics\n3.8,"San Francisco, CA","Paris, France",201 to 500 employees,2005,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1,0,0
886,886,"Scientist, Immuno-Oncology",62-119,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0
887,887,Senior Data Scientist,119-187,At Factual we love all things data! Our missio...,4.3,Factual\n4.3,"Los Angeles, CA","Los Angeles, CA",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,Foursquare,0,0
892,892,Jr. Data Scientist,81-132,MITRE\nis a trusted operator of federally fund...,3.2,MITRE\n3.2,"McLean, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0
893,893,Senior Data Scientist,Employer Provided Salary:120-140,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync\n5.0,"Ann Arbor, MI","Ann Arbor, MI",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,1
895,895,Products Data Analyst II,90-157,TriNet is a leading provider of comprehensive ...,3.3,TriNet\n3.3,"Dublin, CA","Dublin, CA",1001 to 5000 employees,1988,Company - Public,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP",0,0
896,896,Data Architect / Data Modeler,63-110,Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions\n4.3,"New York, NY","New York, NY",1001 to 5000 employees,1999,Company - Public,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle,0,0
897,897,Analytics Manager - Data Mart,42-86,We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health\n3.5,"Scotts Valley, CA","Scotts Valley, CA",501 to 1000 employees,1996,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0
898,898,Lead Data Analyst,32-62,JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost\n3.9,"New York, NY","New York, NY",201 to 500 employees,2010,Company - Private,Internet,Information Technology,$10 to $25 million (USD),-1,0,0
899,899,Data Science Engineer - Mobile,116-208,Mobile is a top strategic priority for Adobe. ...,4.0,Adobe\n4.0,"San Jose, CA","San Jose, CA",10000+ employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft",0,0
900,900,Senior Data Scientist Oncology,107-173,At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0
901,901,Data Scientist,65-113,DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC\n3.4","Olympia, WA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,0,0
902,902,Sr. Data Engineer - Contract-to-Hire (Java),69-127,As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC\n3.0,"Knoxville, TN","Knoxville, TN",10000+ employees,1958,Company - Private,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ...",0,0
904,904,Senior Data Scientist - R&D Oncology,102-172,"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca\n3.9,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0
907,907,Data Engineer,74-124,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0
909,909,Food Scientist - Developer,40-68,Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza\n3.3,"Milwaukee, WI","Milwaukee, WI",501 to 1000 employees,1964,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1,0,0
910,910,Senior Data Engineer,76-142,Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC\n3.2,"Franklin, TN","Indianapolis, IN",1001 to 5000 employees,2004,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,0,0
911,911,Data Engineer,76-142,MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems\n3.4,"Rockville, MD","Reston, VA",201 to 500 employees,1999,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,0,0
912,912,Senior Data Scientist,108-171,"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks\n4.4,"Natick, MA","Natick, MA",1001 to 5000 employees,1984,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1,0,0
913,913,"Director II, Data Science - GRM Actuarial",202-306,Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance\n3.3,"Chicago, IL","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0
914,914,Machine Learning Engineer,91-159,We are seeking a highly-experienced ML Enginee...,3.2,Information Builders\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,1975,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica",0,0
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",80-133,"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,21-34 Per Hour,Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
920,920,"Scientist, Molecular/Cellular Biologist",49-97,"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,...",0,0
921,921,Staff Scientist-Downstream Process Development,49-113,ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1,0,0
924,924,Data Scientist,96-161,SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0
926,926,Scientist - Analytical Services,65-134,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0
928,928,"Associate Scientist / Sr. Associate Scientist,...",59-125,"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat...",0,0
929,929,Associate Data Analyst- Graduate Development P...,32-59,Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0
930,930,Sr. Data Engineer,87-158,Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0
931,931,Clinical Data Analyst,27-48,Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth",0,0
932,932,IT Associate Data Analyst,39-69,"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0
933,933,Business Data Analyst,36-71,(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",0,0
934,934,Senior Insurance Data Scientist,107-173,"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1,0,0
935,935,Senior Data Science Systems Engineer,56-99,"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:25-28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1,1,1
938,938,Senior Scientist - Regulatory Submissions,80-155,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0
939,939,Scientist - Biomarker and Flow Cytometry,43-98,"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1,0,0
940,940,Revenue Analytics Manager,45-78,HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1,0,0
941,941,Sr. Scientist Method Development,50-110,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0
942,942,"Associate Scientist, LC/MS Biologics",44-96,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:100-140,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,0,1
944,944,IT - Data Engineer II,61-119,IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1,0,0
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,0
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,0,0
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0,0
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0,0
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0

In [20]:
df_modified["hourly"]

0      0
1      0
2      0
3      0
4      0
      ..
950    0
951    0
952    0
953    0
955    0
Name: hourly, Length: 742, dtype: int64

#### Remove all 'per hour' and 'employer provided salary:' words in Salary Estimate

In [21]:
#df_modified["Salary Estimate"] = [x.lower().replace('per hour', '').replace('employer provided salary:', '') for x in df_modified["Salary Estimate"]]
df_modified["Salary Estimate"] = df_modified["Salary Estimate"].apply(lambda x: x.lower().replace('per hour', '').replace("employer provided salary:", ''))

<ipython-input-21-feb30b14817f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Salary Estimate"] = df_modified["Salary Estimate"].apply(lambda x: x.lower().replace('per hour', '').replace("employer provided salary:", ''))

In [22]:
df_modified.tail(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided
875,875,Clinical Laboratory Scientist,24-39,POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health\n3.7,"Vail, CO","Vail, CO",501 to 1000 employees,1966,Hospital,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
877,877,"Data Analyst 1, full-time contract worker for ...",35-65,"Purposes\n\nIn addition to your application, p...",4.2,The Church of Jesus Christ of Latter-day Saint...,"Salt Lake City, UT","Salt Lake City, UT",10000+ employees,-1,Nonprofit Organization,Religious Organizations,Non-Profit,Unknown / Non-Applicable,-1,0,0
878,878,Data Scientist,77-132,"Crossix is seeking intellectually curious, res...",3.5,Crossix Solutions\n3.5,"New York, NY","New York, NY",201 to 500 employees,2005,Company - Public,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0
879,879,Data Scientist,51-88,Job Description Header 2 Data scientist Locati...,4.3,Solugenix Corporation\n4.3,"Phoenix, AZ","Brea, CA",201 to 500 employees,1969,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,0,0
880,880,Data Scientist,101-141,American Career College and West Coast Univers...,2.6,West Coast University\n2.6,"Irvine, CA","Irvine, CA",10000+ employees,1997,Company - Private,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0
881,881,Data Engineer - Consultant (Charlotte Based),59-112,Do YOU love working with Data in machine learn...,4.2,Clarity Insights\n4.2,"Charlotte, NC","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0
883,883,Data Engineer,79-147,WHO WE ARE\n\nNCSOFT® established in 1997 and ...,3.1,NCSOFT\n3.1,"Aliso Viejo, CA","Seoul, South Korea",1001 to 5000 employees,1997,Company - Public,Video Games,Media,$10+ billion (USD),"Blizzard Entertainment, Riot Games, Electronic...",0,0
884,884,Data Scientist (Warehouse Automation),79-127,"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics\n3.8,"San Francisco, CA","Paris, France",201 to 500 employees,2005,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1,0,0
886,886,"Scientist, Immuno-Oncology",62-119,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0
887,887,Senior Data Scientist,119-187,At Factual we love all things data! Our missio...,4.3,Factual\n4.3,"Los Angeles, CA","Los Angeles, CA",51 to 200 employees,2008,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,Foursquare,0,0
892,892,Jr. Data Scientist,81-132,MITRE\nis a trusted operator of federally fund...,3.2,MITRE\n3.2,"McLean, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0
893,893,Senior Data Scientist,120-140,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync\n5.0,"Ann Arbor, MI","Ann Arbor, MI",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,1
895,895,Products Data Analyst II,90-157,TriNet is a leading provider of comprehensive ...,3.3,TriNet\n3.3,"Dublin, CA","Dublin, CA",1001 to 5000 employees,1988,Company - Public,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP",0,0
896,896,Data Architect / Data Modeler,63-110,Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions\n4.3,"New York, NY","New York, NY",1001 to 5000 employees,1999,Company - Public,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle,0,0
897,897,Analytics Manager - Data Mart,42-86,We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health\n3.5,"Scotts Valley, CA","Scotts Valley, CA",501 to 1000 employees,1996,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0
898,898,Lead Data Analyst,32-62,JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost\n3.9,"New York, NY","New York, NY",201 to 500 employees,2010,Company - Private,Internet,Information Technology,$10 to $25 million (USD),-1,0,0
899,899,Data Science Engineer - Mobile,116-208,Mobile is a top strategic priority for Adobe. ...,4.0,Adobe\n4.0,"San Jose, CA","San Jose, CA",10000+ employees,1982,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft",0,0
900,900,Senior Data Scientist Oncology,107-173,At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca\n3.9,"Gaithersburg, MD","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0
901,901,Data Scientist,65-113,DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC\n3.4","Olympia, WA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,0,0
902,902,Sr. Data Engineer - Contract-to-Hire (Java),69-127,As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC\n3.0,"Knoxville, TN","Knoxville, TN",10000+ employees,1958,Company - Private,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ...",0,0
904,904,Senior Data Scientist - R&D Oncology,102-172,"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca\n3.9,"New York, NY","Cambridge, United Kingdom",10000+ employees,1913,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0
907,907,Data Engineer,74-124,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0
909,909,Food Scientist - Developer,40-68,Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza\n3.3,"Milwaukee, WI","Milwaukee, WI",501 to 1000 employees,1964,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1,0,0
910,910,Senior Data Engineer,76-142,Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC\n3.2,"Franklin, TN","Indianapolis, IN",1001 to 5000 employees,2004,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,0,0
911,911,Data Engineer,76-142,MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems\n3.4,"Rockville, MD","Reston, VA",201 to 500 employees,1999,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,0,0
912,912,Senior Data Scientist,108-171,"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks\n4.4,"Natick, MA","Natick, MA",1001 to 5000 employees,1984,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1,0,0
913,913,"Director II, Data Science - GRM Actuarial",202-306,Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance\n3.3,"Chicago, IL","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0
914,914,Machine Learning Engineer,91-159,We are seeking a highly-experienced ML Enginee...,3.2,Information Builders\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,1975,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica",0,0
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",80-133,"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,21-34,Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
920,920,"Scientist, Molecular/Cellular Biologist",49-97,"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,...",0,0
921,921,Staff Scientist-Downstream Process Development,49-113,ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1,0,0
924,924,Data Scientist,96-161,SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0
926,926,Scientist - Analytical Services,65-134,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0
928,928,"Associate Scientist / Sr. Associate Scientist,...",59-125,"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat...",0,0
929,929,Associate Data Analyst- Graduate Development P...,32-59,Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0
930,930,Sr. Data Engineer,87-158,Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0
931,931,Clinical Data Analyst,27-48,Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth",0,0
932,932,IT Associate Data Analyst,39-69,"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0
933,933,Business Data Analyst,36-71,(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",0,0
934,934,Senior Insurance Data Scientist,107-173,"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1,0,0
935,935,Senior Data Science Systems Engineer,56-99,"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,25-28,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1,1,1
938,938,Senior Scientist - Regulatory Submissions,80-155,British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0
939,939,Scientist - Biomarker and Flow Cytometry,43-98,"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1,0,0
940,940,Revenue Analytics Manager,45-78,HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1,0,0
941,941,Sr. Scientist Method Development,50-110,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0
942,942,"Associate Scientist, LC/MS Biologics",44-96,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0
943,943,"Research Scientist, Immunology - Cancer Biology",100-140,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,0,1
944,944,IT - Data Engineer II,61-119,IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1,0,0
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,0
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,0,0
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0,0
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0,0
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0

#### Create a new column called 'min salary' to show minimum salary

In [23]:
#df_modified['min_salary'] = [x.split('-')[0] for x in df_modified["Salary Estimate"]]
df_modified["min_salary"] = df_modified["Salary Estimate"].apply(lambda x: x.split("-")[0])

<ipython-input-23-586bbe2a485b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["min_salary"] = df_modified["Salary Estimate"].apply(lambda x: x.split("-")[0])

In [24]:
df_modified

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0,58
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0,72
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0,56
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,95
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0,61

#### Create a 'max salary' column to show maximum salary

In [25]:
df_modified["max_salary"]= [x.split('-')[1] for x in df_modified["Salary Estimate"]]

<ipython-input-25-6e89d900e4f5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["max_salary"]= [x.split('-')[1] for x in df_modified["Salary Estimate"]]

In [26]:
df_modified.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143

#### Convert the 'min salary' column into the interger data type

In [27]:
df_modified["min_salary"] = df_modified["min_salary"].astype('int')

<ipython-input-27-b866ebe9431b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["min_salary"] = df_modified["min_salary"].astype('int')

#### Convert the 'max salary' column into the interger data type

In [28]:
df_modified["max_salary"] = df_modified["max_salary"].astype('int')

<ipython-input-28-958fa301c81c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["max_salary"] = df_modified["max_salary"].astype('int')

#### Find the average salary

In [29]:
df_modified["avg_salary"] = (df_modified.min_salary+df_modified.max_salary)/2

<ipython-input-29-8acd89e7d662>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["avg_salary"] = (df_modified.min_salary+df_modified.max_salary)/2

In [30]:
df_modified.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5

#### Multiply the 'min salary' column values by 1000 (remember we removed 'K' which represented a 1000)

In [31]:
df_modified["min_salary"] = [x*1000 for x in df_modified["min_salary"]]

<ipython-input-31-0e736d37065d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["min_salary"] = [x*1000 for x in df_modified["min_salary"]]

In [32]:
df_modified.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53000,91,72.0
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63000,112,87.5
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80000,90,85.0
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97,76.5
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143,114.5

#### Multiply the 'max salary' column values by 1000

In [33]:
df_modified["max_salary"] = [x*1000 for x in df_modified["max_salary"]]

<ipython-input-33-4c6778077d3e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["max_salary"] = [x*1000 for x in df_modified["max_salary"]]

#### Multipy the 'avg salary' column values by 1000

In [34]:
df_modified["avg_salary"] = [x*1000 for x in df_modified["avg_salary"]]

<ipython-input-34-885d44b3943c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["avg_salary"] = [x*1000 for x in df_modified["avg_salary"]]

In [36]:
df_modified.head(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53000,91000,72000.0
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63000,112000,87500.0
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80000,90000,85000.0
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0
5,5,Data Scientist,71-119,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71000,119000,95000.0
6,6,Data Scientist,54-93,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54000,93000,73500.0
7,7,Data Scientist,86-142,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86000,142000,114000.0
8,8,Research Scientist,38-84,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38000,84000,61000.0
9,9,Data Scientist,120-160,isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120000,160000,140000.0
10,10,Data Scientist,126-201,"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126000,201000,163500.0
11,11,Data Scientist,64-106,"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64000,106000,85000.0
12,12,Staff Data Scientist - Technology,106-172,Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106000,172000,139000.0
13,13,Data Analyst,46-85,"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46000,85000,65500.0
14,14,Data Scientist,83-144,Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83000,144000,113500.0
15,15,Data Engineer I,102-190,This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102000,190000,146000.0
16,16,"Scientist I/II, Biology",67-137,"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67000,137000,102000.0
17,17,Customer Data Scientist,118-189,Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118000,189000,153500.0
18,18,Data Scientist - Health Data Analytics,110-175,"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110000,175000,142500.0
19,19,Data Scientist,64-111,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64000,111000,87500.0
20,20,Data Scientist,81-130,About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81000,130000,105500.0
21,21,Senior Data Scientist / Machine Learning,73-119,IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73000,119000,96000.0
22,22,Data Scientist - Quantitative,86-139,Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86000,139000,112500.0
23,23,Data Scientist,63-105,Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63000,105000,84000.0
25,25,Data Scientist,109-177,Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109000,177000,143000.0
26,26,Digital Health Data Scientist,63-110,ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63000,110000,86500.0
27,27,Data Scientist,75-124,As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75000,124000,99500.0
28,28,Associate Data Analyst,34-61,"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34000,61000,47500.0
29,29,Clinical Data Scientist,63-105,THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63000,105000,84000.0
30,30,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80000,90000,85000.0
31,31,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0
32,32,Data Scientist,72-120,Preferred Qualifications\nMasters degree or do...,3.6,Amrock\n3.6,"Detroit, MI","Detroit, MI",1001 to 5000 employees,1997,Company - Private,Real Estate,Real Estate,$500 million to $1 billion (USD),-1,0,0,72000,120000,96000.0
33,33,Data Scientist / Machine Learning Expert,86-143,Posting Title\nData Scientist / Machine Learni...,3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86000,143000,114500.0
34,34,Data Scientist,93-149,"Title: Software Engineer, Data Science\n\nDesi...",3.8,Juniper Networks\n3.8,"Sunnyvale, CA","Sunnyvale, CA",5001 to 10000 employees,1996,Company - Public,Telecommunications Services,Telecommunications,$2 to $5 billion (USD),-1,0,0,93000,149000,121000.0
35,35,Data Scientist,85-140,New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs\n4.7,"Ipswich, MA","Ipswich, MA",201 to 500 employees,1974,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85000,140000,112500.0
36,36,Web Data Analyst,77-135,We are looking for a Web Data Analyst to assis...,4.2,Clarity Insights\n4.2,"San Jose, CA","Chicago, IL",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,77000,135000,106000.0
37,37,Data Scientist,82-132,Overview\n\n\nAre you passionate about changin...,3.5,Esri\n3.5,"Redlands, CA","Redlands, CA",1001 to 5000 employees,1969,Company - Private,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82000,132000,107000.0
38,38,Data Scientist,83-137,STR is a government research contractor specia...,4.7,Systems & Technology Research\n4.7,"Woburn, MA","Woburn, MA",201 to 500 employees,2010,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83000,137000,110000.0
39,39,Senior Data Scientist,115-180,"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius\n3.5,"Fremont, CA","Gottingen, Germany",5001 to 10000 employees,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115000,180000,147500.0
40,40,Data Engineer,74-138,Lancer Insurance Company is looking for a Data...,3.5,Lancer Insurance\n3.5,"Long Beach, NY","Long Beach, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,74000,138000,106000.0
41,41,Data Analyst,64-112,About the Role:\n\nThe Data Analyst plays a cr...,4.2,Sauce Labs\n4.2,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64000,112000,88000.0
43,43,Data Engineer,68-129,Position Title: Data Engineer\n\nPersivia is s...,3.6,Persivia\n3.6,"Marlborough, MA","Lowell, MA",1 to 50 employees,-1,Company - Private,-1,-1,Less than $1 million (USD),-1,0,0,68000,129000,98500.0
44,44,Data Scientist - Algorithms & Inference,110-175,"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110000,175000,142500.0
45,45,Scientist,52-113,"We are a global team of 6000 visionaries, doer...",3.4,Edgewell Personal Care\n3.4,"Allendale, NJ","Shelton, CT",5001 to 10000 employees,2015,Company - Public,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52000,113000,82500.0
46,46,Senior Data Scientist,110-150,"Working for Equity Residential (EQR), a leadin...",4.3,Equity Residential\n4.3,"Chicago, IL","Chicago, IL",1001 to 5000 employees,1993,Company - Public,Real Estate,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110000,150000,130000.0
48,48,Data Scientist,150-160,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services\n5.0,"Washington, DC","Alexandria, VA",Unknown,-1,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,1,150000,160000,155000.0
49,49,Lead Data Scientist,158-211,As the world's leader in digital payments tech...,3.7,Visa Inc.\n3.7,"Bellevue, WA","Foster City, CA",10000+ employees,1958,Company - Public,IT Services,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158000,211000,184500.0
50,50,Associate Data Analyst,20-39,Intrado is looking for an Associate Data Analy...,3.1,Intrado\n3.1,"Longmont, CO","Omaha, NE",5001 to 10000 employees,1986,Company - Private,Enterprise Software & Network Solutions,Information Technology,$2 to $5 billion (USD),-1,0,0,20000,39000,29500.0
51,51,Spectral Scientist/Engineer,56-117,Thank you for your interest in joining the Cen...,4.7,Centauri\n4.7,"Beavercreek, OH","Chantilly, VA",501 to 1000 employees,1999,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56000,117000,86500.0
52,52,College Hire - Data Scientist - Open to Decemb...,63-99,Description\n\nCaterpillar's legacy of industr...,3.7,Caterpillar\n3.7,"Peoria, IL","Deerfield, IL",10000+ employees,1925,Company - Public,Industrial Manufacturing,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63000,99000,81000.0
54,54,Data Scientist,68-114,"Overview:\n\nBlazing a new trail, we are furth...",3.8,Zimmerman Advertising\n3.8,"Fort Lauderdale, FL","Fort Lauderdale, FL",501 to 1000 employees,1984,Subsidiary or Business Segment,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,68000,114000,91000.0
55,55,"Data Scientist, Office of Data Science",86-143,Help shape the future of Data Science across L...,3.3,Liberty Mutual Insurance\n3.3,"Boston, MA","Boston, MA",10000+ employees,1912,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0,86000,143000,114500.0
56,56,Data Science Analyst,41-95,Torch Technologies is seeking a Junior- to MId...,4.6,"Torch Technologies, Inc.\n4.6","Huntsville, AL","Huntsville, AL",1001 to 5000 employees,2002,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,41000,95000,68000.0
57,57,Data Scientist,86-144,About Swiss Re\n\nThe Swiss Re Group is one of...,3.7,Swiss Re\n3.7,"Armonk, NY","Zurich, Switzerland",10000+ employees,1863,Company - Public,Insurance Agencies & Brokerages,Insurance,$10+ billion (USD),"Munich Re, Hannover RE, SCOR",0,0,86000,144000,115000.0
58,58,Data Scientist,80-139,At Northrop Grumman we develop cutting-edge te...,3.7,Northrop Grumman\n3.7,"San Diego, CA","Falls Church, VA",10000+ employees,1939,Company - Public,Aerospace & Defense,Aerospace & Defense,$10+ billion (USD),-1,0,0,80000,139000,109500.0
59,59,Data Scientist,56-95,"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius\n3.5,"Albuquerque, NM","Gottingen, Germany",5001 to 10000 employees,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,56000,95000,75500.0
60,60,Data Scientist,120-189,"About Netskope\n\nToday, there's more data and...",4.1,Netskope\n4.1,"San Francisco, CA","Santa Clara, CA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,"Skyhigh Networks, Zscaler, NortonLifeLock",0,0,120000,189000,154500.0
61,61,Data Scientist,111-176,About Us\n\n\nInterested in working for a huma...,4.7,1904labs\n4.7,"Saint Louis, MO","Saint Louis, MO",51 to 200 employees,2016,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,"Slalom, Daugherty Business Solutions",0,0,111000,176000,143500.0
62,62,Data Scientist,54-93,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54000,93000,73500.0
63,63,Data Scientist,71-119,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71000,119000,95000.0

#### Display all rows of the DataFrame

In [37]:
pd.set_option('display.max_rows', None)

In [38]:
df_modified

     Unnamed: 0                                          Job Title  \
0             0                                     Data Scientist
1             1                          Healthcare Data Scientist
2             2                                     Data Scientist
3             3                                     Data Scientist
4             4                                     Data Scientist
5             5                                     Data Scientist
6             6                                     Data Scientist
7             7                                     Data Scientist
8             8                                 Research Scientist
9             9                                     Data Scientist
10           10                                     Data Scientist
11           11                                     Data Scientist
12           12                  Staff Data Scientist - Technology
13           13                                       Data Analyst
14           14                                     Data Scientist
15           15                                    Data Engineer I
16           16                            Scientist I/II, Biology
17           17                            Customer Data Scientist
18           18             Data Scientist - Health Data Analytics
19           19                                     Data Scientist
20           20                                     Data Scientist
21           21           Senior Data Scientist / Machine Learning
22           22                      Data Scientist - Quantitative
23           23                                     Data Scientist
25           25                                     Data Scientist
26           26                      Digital Health Data Scientist
27           27                                     Data Scientist
28           28                             Associate Data Analyst
29           29                            Clinical Data Scientist
30           30                                     Data Scientist
31           31                                     Data Scientist
32           32                                     Data Scientist
33           33           Data Scientist / Machine Learning Expert
34           34                                     Data Scientist
35           35                                     Data Scientist
36           36                                   Web Data Analyst
37           37                                     Data Scientist
38           38                                     Data Scientist
39           39                              Senior Data Scientist
40           40                                      Data Engineer
41           41                                       Data Analyst
43           43                                      Data Engineer
44           44            Data Scientist - Algorithms & Inference
45           45                                          Scientist
46           46                              Senior Data Scientist
48           48                                     Data Scientist
49           49                                Lead Data Scientist
50           50                             Associate Data Analyst
51           51                        Spectral Scientist/Engineer
52           52  College Hire - Data Scientist - Open to Decemb...
54           54                                     Data Scientist
55           55             Data Scientist, Office of Data Science
56           56                               Data Science Analyst
57           57                                     Data Scientist
58           58                                     Data Scientist
59           59                                     Data Scientist
60           60                                     Data Scientist
61           61                                     Data Scientist
62           62                                     Data Scientist
63           63                                     Data Scientist
65           65                              Senior Data Scientist
66           66                                     Data Scientist
67           67                         Senior Risk Data Scientist
68           68  Data Scientist in Artificial Intelligence Earl...
70           70                                     Data Scientist
72           72                                     Data Scientist
73           73                                     Data Scientist
75           75                          Data Scientist - Research
76           76                                     Data Scientist
77           77                        R&D Data Analysis Scientist
78           78                               Analytics Consultant
79           79                             Director, Data Science
80           80                                          Scientist
81           81                                  Data Scientist SR
82           82                                     Data Scientist
83           83                              R&D Sr Data Scientist
84           84        Customer Data Scientist/Sales Engineer (Bay
85           85                                 Research Scientist
86           86                                     Data Scientist
87           87                                     Data Scientist
88           88                                     Data Scientist
89           89                          Jr. Business Data Analyst
90           90                                     Data Scientist
91           91                                       Data Analyst
92           92                                      Data Engineer
93           93                                       Data Analyst
94           94                  Staff Data Scientist - Technology
95           95                                     Data Scientist
96           96                                     Data Scientist
97           97                         Data Management Specialist
99           99                            E-Commerce Data Analyst
101         101                                   Sr. Scientist II
102         102                           Insurance Data Scientist
104         104                                       Data Modeler
105         105                           Data Analyst / Scientist
106         106                                          Scientist
107         107                                     Data Scientist
108         108                                     Data Scientist
109         109                                       Data Analyst
110         110                                Lead Data Scientist
112         112                                     Data Scientist
113         113                                     Data Scientist
116         116                    Data Scientist, Rice University
117         117                              Senior Data Scientist
118         118                                      Data Engineer
119         119                              Senior Data Scientist
120         120                             Financial Data Analyst
122         122                                Senior Data Analyst
123         123                                 Research Scientist
124         124                                     Data Scientist
125         125                                      Data Engineer
126         126                                     Data Scientist
127         127                                     Data Scientist
128         128                                     Data Scientist
129         129                                      Data Engineer
130         130                                  Ag Data Scientist
131         131                                     Data Scientist
132         132                                      Data Engineer
136         136                                  Data Scientist II
137         137                               Senior Data Engineer
138         138                                     Data Scientist
139         139                                     Data Scientist
140         140                                      Data Engineer
141         141                                      Data Engineer
142         142                                       Data Analyst
143         143                                  Project Scientist
145         145                                     Data Scientist
146         146                             Data Analytics Manager
147         147  Senior Machine Learning (ML) Engineer / Data S...
148         148                                     Data Scientist
150         150                              Senior Data Scientist
152         152                                     Data Scientist
153         153                                Associate Scientist
154         154                       Scientist 2, QC Viral Vector
156         156                          Machine Learning Engineer
157         157                         Data Scientist/ML Engineer
158         158                                     Data Scientist
159         159                            Customer Data Scientist
161         161                                      Data Engineer
162         162                                      Data Engineer
164         164                                 Sr. Data Scientist
166         166                         Data Engineer 4 - Contract
167         167                    Data Analyst - Asset Management
168         168  Senior Research Scientist - Embedded System De...
169         169                    Data Scientist - Bioinformatics
170         170                                      Data Engineer
171         171             Customer Data Scientist/Sales Engineer
172         172                                Lead Data Scientist
174         174                           MongoDB Data Engineer II
175         175                   Senior Data Scientist Statistics
177         177                                Senior Data Analyst
178         178               Senior Spark Engineer (Data Science)
179         179                                      Data Engineer
180         180                    BI & Platform Analytics Manager
181         181                                Lead Data Scientist
182         182  Sr. Data Scientist - Analytics, Personalized H...
183         183                              Senior Data Scientist
185         185  Pricipal Scientist Molecular and cellular biol...
187         187               Data Scientist (Actuary, FSA or ASA)
188         188                               Staff Data Scientist
190         190           Senior Data Scientist / Machine Learning
191         191             Data Scientist - Health Data Analytics
192         192                Data Engineer 5 - Contract (Remote)
193         193                    Senior Scientist - Neuroscience
194         194                                Senior Data Analyst
197         197                              Medical Lab Scientist
198         198              Risk and Analytics IT, Data Scientist
199         199                  Scientist, Analytical Development
200         200                              Senior Data Scientist
201         201                                  Analytics Manager
202         202                                      Data Engineer
203         203         Digital Marketing & ECommerce Data Analyst
204         204  Sr. Scientist - Digital & Image Analysis/Compu...
205         205                                Senior Data Analyst
206         206                 Principal Scientist - Immunologist
207         207                              Senior Data Scientist
208         208  Principal Data Scientist with over 10 years ex...
209         209                MED TECH/LAB SCIENTIST - LABORATORY
210         210  Sr. Scientist, Quantitative Translational Scie...
211         211                              Sr. Data Scientist II
212         212                     Excel / VBA / SQL Data Analyst
213         213                Machine Learning Research Scientist
215         215                                   VP, Data Science
216         216                              Senior Data Scientist
217         217                                 Radar Data Analyst
221         221                   PL Actuarial-Lead Data Scientist
223         223                                       PV Scientist
224         224           Senior Data & Machine Learning Scientist
225         225  Principal Data Scientist (Computational Chemis...
226         226                                      Data Engineer
228         228        Principal Scientist, Chemistry & Immunology
229         229             Software Engineer - Data Visualization
230         230             Scientist/Senior Scientist, Autoimmune
233         233                    Staff Machine Learning Engineer
234         234                    Principal Scientist, Hematology
235         235                                 Lead Data Engineer
239         239                             Marketing Data Analyst
240         240                       Medical Laboratory Scientist
242         242                     R&D Specialist/ Food Scientist
243         243         Senior Research Scientist-Machine Learning
245         245                      Analytics Manager - Data Mart
246         246        Sr. Data Engineer - Contract-to-Hire (Java)
247         247          MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB
248         248                         Food Scientist - Developer
250         250     Staff Scientist-Downstream Process Development
251         251                                  Sr. Data Engineer
253         253                      Data Scientist - Quantitative
254         254                                     Data Scientist
255         255       Senior Research Statistician- Data Scientist
256         256                         Business Data Analyst, SQL
257         257  Medical Technologist / Clinical Laboratory Sci...
258         258                                     Data Scientist
259         259                                Senior Data Analyst
260         260                    BI & Platform Analytics Manager
262         262                                      Data Engineer
263         263                                     Data Scientist
264         264                                       Data Analyst
265         265        Associate Data Scientist/Computer Scientist
266         266          Business Intelligence Analyst / Developer
267         267                                Lead Data Scientist
268         268  Sr. Data Scientist - Analytics, Personalized H...
269         269                              Senior Data Scientist
270         270                                       Data Analyst
273         273  Pricipal Scientist Molecular and cellular biol...
274         274                                       Data Analyst
275         275                                       Data Analyst
276         276                               Staff Data Scientist
277         277               Data Scientist (Actuary, FSA or ASA)
278         278                            System and Data Analyst
281         281                                     Data Scientist
282         282                Data Engineer 5 - Contract (Remote)
284         284                      Digital Health Data Scientist
285         285                                     Data Scientist
288         288                  Data & Analytics Consultant (NYC)
289         289                    Senior Scientist - Neuroscience
290         290                                      Data Engineer
291         291   Big Data Engineer - Chicago - Future Opportunity
292         292                                Senior Data Analyst
293         293                                     Data Scientist
295         295                                Survey Data Analyst
296         296                                     Data Scientist
299         299                                     Data Scientist
300         300              Risk and Analytics IT, Data Scientist
302         302                                     Data Scientist
305         305               Lead Health Data Analyst - Front End
306         306                                 Research Scientist
307         307                              Medical Lab Scientist
308         308                                Junior Data Analyst
309         309                                  SQL Data Engineer
310         310                                     Data Scientist
311         311                              Senior Data Scientist
312         312                                     Data Scientist
313         313                  Scientist, Analytical Development
314         314                                  Analytics Manager
316         316                            Clinical Data Scientist
317         317                                     Data Scientist
318         318     Sr. Data Scientist, Cyber-Security LT Contract
319         319                                      Data Engineer
320         320                                     Data Scientist
322         322  Sr. Scientist - Digital & Image Analysis/Compu...
323         323         Digital Marketing & ECommerce Data Analyst
324         324                 Principal Scientist - Immunologist
325         325                                Senior Data Analyst
326         326                   Insurance Financial Data Analyst
328         328                                     Data Scientist
330         330                                     Data Scientist
331         331  Principal Data Scientist with over 10 years ex...
332         332                                      Data Engineer
333         333                              Senior Data Scientist
334         334                            Data Engineer I - Azure
335         335  Sr. Scientist, Quantitative Translational Scie...
337         337                MED TECH/LAB SCIENTIST - LABORATORY
339         339                              Sr. Data Scientist II
341         341                                     Data Scientist
342         342                  Information Security Data Analyst
344         344                     Excel / VBA / SQL Data Analyst
346         346                Machine Learning Research Scientist
347         347                                     Data Scientist
348         348                                     Data Scientist
349         349                                     Data Scientist
350         350                                     Data Scientist
351         351                              Senior Data Scientist
352         352                             Data Scientist, Senior
353         353                              Senior Data Scientist
354         354                                   VP, Data Science
355         355                                 Radar Data Analyst
356         356                   CONSULTANT– DATA ANALYTICS GROUP
357         357                                      Data Engineer
358         358                              Senior Data Scientist
362         362  Data Engineer, Data Engineering and Artifical ...
364         364                                    Staff Scientist
366         366                   PL Actuarial-Lead Data Scientist
367         367  Associate Scientist/Scientist, Process Analyti...
368         368                                   Sr. Data Analyst
369         369           Senior Data & Machine Learning Scientist
370         370                               Program/Data Analyst
371         371                                      Data Engineer

#### Remove the unwanted characters in the 'Company Name' column

In [39]:
df_modified["Company Name"]= [x if x in df_modified["Rating"]<0 else x[:-4] for x in df_modified["Company Name"]]

<ipython-input-39-8b628ec5c476>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Company Name"]= [x if x in df_modified["Rating"]<0 else x[:-4] for x in df_modified["Company Name"]]

In [40]:
df_modified.head(5)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53000,91000,72000.0
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63000,112000,87500.0
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80000,90000,85000.0
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0

#### Get the Location names- remove state names

In [41]:
df_modified["Location"] = [x.split(",")[0] for x in df_modified["Location"]]

<ipython-input-41-879163a6322b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Location"] = [x.split(",")[0] for x in df_modified["Location"]]

#### Get the Headquarters- remove state names

In [42]:
df_modified["Headquarters"] = [x.split(',')[0] for x in df_modified["Headquarters"]]

<ipython-input-42-617eb4d7b9b2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Headquarters"] = [x.split(',')[0] for x in df_modified["Headquarters"]]

In [43]:
df_modified

     Unnamed: 0                                          Job Title  \
0             0                                     Data Scientist
1             1                          Healthcare Data Scientist
2             2                                     Data Scientist
3             3                                     Data Scientist
4             4                                     Data Scientist
5             5                                     Data Scientist
6             6                                     Data Scientist
7             7                                     Data Scientist
8             8                                 Research Scientist
9             9                                     Data Scientist
10           10                                     Data Scientist
11           11                                     Data Scientist
12           12                  Staff Data Scientist - Technology
13           13                                       Data Analyst
14           14                                     Data Scientist
15           15                                    Data Engineer I
16           16                            Scientist I/II, Biology
17           17                            Customer Data Scientist
18           18             Data Scientist - Health Data Analytics
19           19                                     Data Scientist
20           20                                     Data Scientist
21           21           Senior Data Scientist / Machine Learning
22           22                      Data Scientist - Quantitative
23           23                                     Data Scientist
25           25                                     Data Scientist
26           26                      Digital Health Data Scientist
27           27                                     Data Scientist
28           28                             Associate Data Analyst
29           29                            Clinical Data Scientist
30           30                                     Data Scientist
31           31                                     Data Scientist
32           32                                     Data Scientist
33           33           Data Scientist / Machine Learning Expert
34           34                                     Data Scientist
35           35                                     Data Scientist
36           36                                   Web Data Analyst
37           37                                     Data Scientist
38           38                                     Data Scientist
39           39                              Senior Data Scientist
40           40                                      Data Engineer
41           41                                       Data Analyst
43           43                                      Data Engineer
44           44            Data Scientist - Algorithms & Inference
45           45                                          Scientist
46           46                              Senior Data Scientist
48           48                                     Data Scientist
49           49                                Lead Data Scientist
50           50                             Associate Data Analyst
51           51                        Spectral Scientist/Engineer
52           52  College Hire - Data Scientist - Open to Decemb...
54           54                                     Data Scientist
55           55             Data Scientist, Office of Data Science
56           56                               Data Science Analyst
57           57                                     Data Scientist
58           58                                     Data Scientist
59           59                                     Data Scientist
60           60                                     Data Scientist
61           61                                     Data Scientist
62           62                                     Data Scientist
63           63                                     Data Scientist
65           65                              Senior Data Scientist
66           66                                     Data Scientist
67           67                         Senior Risk Data Scientist
68           68  Data Scientist in Artificial Intelligence Earl...
70           70                                     Data Scientist
72           72                                     Data Scientist
73           73                                     Data Scientist
75           75                          Data Scientist - Research
76           76                                     Data Scientist
77           77                        R&D Data Analysis Scientist
78           78                               Analytics Consultant
79           79                             Director, Data Science
80           80                                          Scientist
81           81                                  Data Scientist SR
82           82                                     Data Scientist
83           83                              R&D Sr Data Scientist
84           84        Customer Data Scientist/Sales Engineer (Bay
85           85                                 Research Scientist
86           86                                     Data Scientist
87           87                                     Data Scientist
88           88                                     Data Scientist
89           89                          Jr. Business Data Analyst
90           90                                     Data Scientist
91           91                                       Data Analyst
92           92                                      Data Engineer
93           93                                       Data Analyst
94           94                  Staff Data Scientist - Technology
95           95                                     Data Scientist
96           96                                     Data Scientist
97           97                         Data Management Specialist
99           99                            E-Commerce Data Analyst
101         101                                   Sr. Scientist II
102         102                           Insurance Data Scientist
104         104                                       Data Modeler
105         105                           Data Analyst / Scientist
106         106                                          Scientist
107         107                                     Data Scientist
108         108                                     Data Scientist
109         109                                       Data Analyst
110         110                                Lead Data Scientist
112         112                                     Data Scientist
113         113                                     Data Scientist
116         116                    Data Scientist, Rice University
117         117                              Senior Data Scientist
118         118                                      Data Engineer
119         119                              Senior Data Scientist
120         120                             Financial Data Analyst
122         122                                Senior Data Analyst
123         123                                 Research Scientist
124         124                                     Data Scientist
125         125                                      Data Engineer
126         126                                     Data Scientist
127         127                                     Data Scientist
128         128                                     Data Scientist
129         129                                      Data Engineer
130         130                                  Ag Data Scientist
131         131                                     Data Scientist
132         132                                      Data Engineer
136         136                                  Data Scientist II
137         137                               Senior Data Engineer
138         138                                     Data Scientist
139         139                                     Data Scientist
140         140                                      Data Engineer
141         141                                      Data Engineer
142         142                                       Data Analyst
143         143                                  Project Scientist
145         145                                     Data Scientist
146         146                             Data Analytics Manager
147         147  Senior Machine Learning (ML) Engineer / Data S...
148         148                                     Data Scientist
150         150                              Senior Data Scientist
152         152                                     Data Scientist
153         153                                Associate Scientist
154         154                       Scientist 2, QC Viral Vector
156         156                          Machine Learning Engineer
157         157                         Data Scientist/ML Engineer
158         158                                     Data Scientist
159         159                            Customer Data Scientist
161         161                                      Data Engineer
162         162                                      Data Engineer
164         164                                 Sr. Data Scientist
166         166                         Data Engineer 4 - Contract
167         167                    Data Analyst - Asset Management
168         168  Senior Research Scientist - Embedded System De...
169         169                    Data Scientist - Bioinformatics
170         170                                      Data Engineer
171         171             Customer Data Scientist/Sales Engineer
172         172                                Lead Data Scientist
174         174                           MongoDB Data Engineer II
175         175                   Senior Data Scientist Statistics
177         177                                Senior Data Analyst
178         178               Senior Spark Engineer (Data Science)
179         179                                      Data Engineer
180         180                    BI & Platform Analytics Manager
181         181                                Lead Data Scientist
182         182  Sr. Data Scientist - Analytics, Personalized H...
183         183                              Senior Data Scientist
185         185  Pricipal Scientist Molecular and cellular biol...
187         187               Data Scientist (Actuary, FSA or ASA)
188         188                               Staff Data Scientist
190         190           Senior Data Scientist / Machine Learning
191         191             Data Scientist - Health Data Analytics
192         192                Data Engineer 5 - Contract (Remote)
193         193                    Senior Scientist - Neuroscience
194         194                                Senior Data Analyst
197         197                              Medical Lab Scientist
198         198              Risk and Analytics IT, Data Scientist
199         199                  Scientist, Analytical Development
200         200                              Senior Data Scientist
201         201                                  Analytics Manager
202         202                                      Data Engineer
203         203         Digital Marketing & ECommerce Data Analyst
204         204  Sr. Scientist - Digital & Image Analysis/Compu...
205         205                                Senior Data Analyst
206         206                 Principal Scientist - Immunologist
207         207                              Senior Data Scientist
208         208  Principal Data Scientist with over 10 years ex...
209         209                MED TECH/LAB SCIENTIST - LABORATORY
210         210  Sr. Scientist, Quantitative Translational Scie...
211         211                              Sr. Data Scientist II
212         212                     Excel / VBA / SQL Data Analyst
213         213                Machine Learning Research Scientist
215         215                                   VP, Data Science
216         216                              Senior Data Scientist
217         217                                 Radar Data Analyst
221         221                   PL Actuarial-Lead Data Scientist
223         223                                       PV Scientist
224         224           Senior Data & Machine Learning Scientist
225         225  Principal Data Scientist (Computational Chemis...
226         226                                      Data Engineer
228         228        Principal Scientist, Chemistry & Immunology
229         229             Software Engineer - Data Visualization
230         230             Scientist/Senior Scientist, Autoimmune
233         233                    Staff Machine Learning Engineer
234         234                    Principal Scientist, Hematology
235         235                                 Lead Data Engineer
239         239                             Marketing Data Analyst
240         240                       Medical Laboratory Scientist
242         242                     R&D Specialist/ Food Scientist
243         243         Senior Research Scientist-Machine Learning
245         245                      Analytics Manager - Data Mart
246         246        Sr. Data Engineer - Contract-to-Hire (Java)
247         247          MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB
248         248                         Food Scientist - Developer
250         250     Staff Scientist-Downstream Process Development
251         251                                  Sr. Data Engineer
253         253                      Data Scientist - Quantitative
254         254                                     Data Scientist
255         255       Senior Research Statistician- Data Scientist
256         256                         Business Data Analyst, SQL
257         257  Medical Technologist / Clinical Laboratory Sci...
258         258                                     Data Scientist
259         259                                Senior Data Analyst
260         260                    BI & Platform Analytics Manager
262         262                                      Data Engineer
263         263                                     Data Scientist
264         264                                       Data Analyst
265         265        Associate Data Scientist/Computer Scientist
266         266          Business Intelligence Analyst / Developer
267         267                                Lead Data Scientist
268         268  Sr. Data Scientist - Analytics, Personalized H...
269         269                              Senior Data Scientist
270         270                                       Data Analyst
273         273  Pricipal Scientist Molecular and cellular biol...
274         274                                       Data Analyst
275         275                                       Data Analyst
276         276                               Staff Data Scientist
277         277               Data Scientist (Actuary, FSA or ASA)
278         278                            System and Data Analyst
281         281                                     Data Scientist
282         282                Data Engineer 5 - Contract (Remote)
284         284                      Digital Health Data Scientist
285         285                                     Data Scientist
288         288                  Data & Analytics Consultant (NYC)
289         289                    Senior Scientist - Neuroscience
290         290                                      Data Engineer
291         291   Big Data Engineer - Chicago - Future Opportunity
292         292                                Senior Data Analyst
293         293                                     Data Scientist
295         295                                Survey Data Analyst
296         296                                     Data Scientist
299         299                                     Data Scientist
300         300              Risk and Analytics IT, Data Scientist
302         302                                     Data Scientist
305         305               Lead Health Data Analyst - Front End
306         306                                 Research Scientist
307         307                              Medical Lab Scientist
308         308                                Junior Data Analyst
309         309                                  SQL Data Engineer
310         310                                     Data Scientist
311         311                              Senior Data Scientist
312         312                                     Data Scientist
313         313                  Scientist, Analytical Development
314         314                                  Analytics Manager
316         316                            Clinical Data Scientist
317         317                                     Data Scientist
318         318     Sr. Data Scientist, Cyber-Security LT Contract
319         319                                      Data Engineer
320         320                                     Data Scientist
322         322  Sr. Scientist - Digital & Image Analysis/Compu...
323         323         Digital Marketing & ECommerce Data Analyst
324         324                 Principal Scientist - Immunologist
325         325                                Senior Data Analyst
326         326                   Insurance Financial Data Analyst
328         328                                     Data Scientist
330         330                                     Data Scientist
331         331  Principal Data Scientist with over 10 years ex...
332         332                                      Data Engineer
333         333                              Senior Data Scientist
334         334                            Data Engineer I - Azure
335         335  Sr. Scientist, Quantitative Translational Scie...
337         337                MED TECH/LAB SCIENTIST - LABORATORY
339         339                              Sr. Data Scientist II
341         341                                     Data Scientist
342         342                  Information Security Data Analyst
344         344                     Excel / VBA / SQL Data Analyst
346         346                Machine Learning Research Scientist
347         347                                     Data Scientist
348         348                                     Data Scientist
349         349                                     Data Scientist
350         350                                     Data Scientist
351         351                              Senior Data Scientist
352         352                             Data Scientist, Senior
353         353                              Senior Data Scientist
354         354                                   VP, Data Science
355         355                                 Radar Data Analyst
356         356                   CONSULTANT– DATA ANALYTICS GROUP
357         357                                      Data Engineer
358         358                              Senior Data Scientist
362         362  Data Engineer, Data Engineering and Artifical ...
364         364                                    Staff Scientist
366         366                   PL Actuarial-Lead Data Scientist
367         367  Associate Scientist/Scientist, Process Analyti...
368         368                                   Sr. Data Analyst
369         369           Senior Data & Machine Learning Scientist
370         370                               Program/Data Analyst
371         371                                      Data Engineer

#### Get the Location with the highest number of job postings

In [44]:
df_modified["Location"].value_counts()

New York               55
San Francisco          49
Cambridge              48
Chicago                32
Boston                 23
San Jose               13
Pittsburgh             12
Rockville              11
Washington             11
Springfield            10
Herndon                10
Richland               10
Winston-Salem          10
San Diego               9
Indianapolis            9
Mountain View           8
South San Francisco     8
Austin                  8
Rochester               7
Palo Alto               7
Huntsville              6
Marlborough             6
Phoenix                 6
Dallas                  6
Charlotte               6
Salt Lake City          6
Gaithersburg            6
Chantilly               6
Worcester               5
Philadelphia            5
Milwaukee               5
Nashville               5
Denver                  5
Cincinnati              5
Seattle                 5
Redlands                4
Millville               4
Clearwater              4
Fort Belvoir            4
Knoxville               4
Durham                  4
Scotts Valley           4
Hoopeston               4
Atlanta                 4
Los Angeles             4
Omaha                   4
Burbank                 4
Owensboro               4
Burleson                4
Arlington               4
Highland                4
Houston                 4
Natick                  3
Tampa                   3
Concord                 3
Hartford                3
Fort Lee                3
Orange                  3
Vail                    3
Albuquerque             3
McLean                  3
Riverton                3
Annapolis Junction      3
Quincy                  3
Armonk                  3
Baltimore               3
Marietta                3
Silver Spring           3
Lenexa                  3
Columbia                3
Hampton                 3
Ithaca                  3
Richfield               3
Beavercreek             3
San Antonio             3
Lafayette               2
Allentown               2
Frederick               2
Alameda                 2
West Palm Beach         2
San Rafael              2
Louisville              2
Ewing                   2
Aliso Viejo             2
Plano                   2
Hamilton                2
Winter Park             2
Saint Louis             2
Maryland Heights        2
Des Moines              2
Fremont                 2
Newton                  2
Jersey City             2
Fort Lauderdale         2
Ipswich                 2
West Reading            2
Clovis                  2
Green Bay               2
Madison                 2
Woodbridge              2
Bellevue                2
Bedford                 2
Westlake                2
Dearborn                2
Franklin                2
Detroit                 2
Dublin                  2
Coraopolis              2
Plymouth Meeting        2
Alexandria              2
Exton                   2
Phila                   2
New Orleans             2
Minneapolis             2
Orlando                 2
Santa Clara             2
Peoria                  2
Charlottesville         2
Hillsboro               2
Blue Bell               2
Sunnyvale               2
Lewes                   2
Cupertino               2
Vancouver               2
Chandler                2
Cedar Rapids            2
Groton                  2
Kansas City             1
Corvallis               1
Matawan                 1
Harrisburg              1
Foster City             1
Ann Arbor               1
Irvine                  1
Waltham                 1
Framingham              1
Lyndhurst               1
Longmont                1
Aurora                  1
Bloomington             1
Portland                1
Dayton                  1
Lake Forest             1
Ashburn                 1
Sheboygan               1
Red Bank                1
Suitland                1
Syracuse                1
Milpitas                1
Roanoke                 1
Southfield              1
Olympia                 1
Portsmouth              1
Carle Place             1
Logan                   1
Scottsdale              1
Pella                   1
Birmingham              1
San Mateo               1
King of Prussia         1
Cherry Hill             1
Holyoke                 1
Raleigh                 1
Long Beach              1
Newark                  1
Santa Fe Springs        1
Watertown               1
Emeryville              1
Meridian                1
Fort Worth              1
Novato                  1
Santa Barbara           1
Woburn                  1
Glen Burnie             1
Brisbane                1
San Ramon               1
Arvada                  1
Chattanooga             1
Tacoma                  1
Landover                1
Patuxent River          1
Providence              1
Miami                   1
Linthicum               1
Allendale               1
Laurel                  1
Parlier                 1
Valencia                1
Alabaster               1
Oakland                 1
Oak Ridge               1
Agoura Hills            1
Port Washington         1
Reston                  1
Boise                   1
Name: Location, dtype: int64

In [45]:
df_modified.tail(10)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation,Palo Alto,Palo Alto,1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1,0,0,80000,142000,111000.0
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360,San Francisco,San Francisco,51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,0,99000,178000,138500.0
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual,Boston,Springfield,5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,0,0,37000,100000,68500.0
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars,San Francisco,San Francisco,201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0,0,62000,113000,87500.0
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA,Plymouth Meeting,Durham,10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0,0,86000,137000,111500.0
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK,Cambridge,Brentford,10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0,58000,111000,84500.0
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite,Nashville,San Francisco,1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0,72000,133000,102500.0
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute,Pittsburgh,Pittsburgh,501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0,56000,91000,73500.0
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC",Allentown,Chadds Ford,1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,95000,160000,127500.0
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute,Beavercreek,Arlington,501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0,61000,126000,93500.0

#### Create a new column 'Same_Location_Hqtrs' to show job postings that have their locations as their headquarters

In [46]:
df_modified["Same_Location_Hqtrs"] = df_modified.apply(lambda x: 1 if x["Location"]== x["Headquarters"] else 0, axis=1)
#**Same_Location_Hqtrs = [1 if x in df_modified["Location"] and df_modified["Headquarters"] else 0 for x in df_modified]

<ipython-input-46-6d8ad8d79563>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Same_Location_Hqtrs"] = df_modified.apply(lambda x: 1 if x["Location"]== x["Headquarters"] else 0, axis=1)

In [47]:
df_modified.tail(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary,Same_Location_Hqtrs
875,875,Clinical Laboratory Scientist,24-39,POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health,Vail,Vail,501 to 1000 employees,1966,...,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0,24000,39000,31500.0,1
877,877,"Data Analyst 1, full-time contract worker for ...",35-65,"Purposes\n\nIn addition to your application, p...",4.2,The Church of Jesus Christ of Latter-day Saints,Salt Lake City,Salt Lake City,10000+ employees,-1,...,Religious Organizations,Non-Profit,Unknown / Non-Applicable,-1,0,0,35000,65000,50000.0,1
878,878,Data Scientist,77-132,"Crossix is seeking intellectually curious, res...",3.5,Crossix Solutions,New York,New York,201 to 500 employees,2005,...,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,77000,132000,104500.0,1
879,879,Data Scientist,51-88,Job Description Header 2 Data scientist Locati...,4.3,Solugenix Corporation,Phoenix,Brea,201 to 500 employees,1969,...,IT Services,Information Technology,$50 to $100 million (USD),-1,0,0,51000,88000,69500.0,0
880,880,Data Scientist,101-141,American Career College and West Coast Univers...,2.6,West Coast University,Irvine,Irvine,10000+ employees,1997,...,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0,101000,141000,121000.0,1
881,881,Data Engineer - Consultant (Charlotte Based),59-112,Do YOU love working with Data in machine learn...,4.2,Clarity Insights,Charlotte,Chicago,201 to 500 employees,2008,...,IT Services,Information Technology,Unknown / Non-Applicable,-1,0,0,59000,112000,85500.0,0
883,883,Data Engineer,79-147,WHO WE ARE\n\nNCSOFT® established in 1997 and ...,3.1,NCSOFT,Aliso Viejo,Seoul,1001 to 5000 employees,1997,...,Video Games,Media,$10+ billion (USD),"Blizzard Entertainment, Riot Games, Electronic...",0,0,79000,147000,113000.0,0
884,884,Data Scientist (Warehouse Automation),79-127,"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics,San Francisco,Paris,201 to 500 employees,2005,...,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1,0,0,79000,127000,103000.0,0
886,886,"Scientist, Immuno-Oncology",62-119,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK,Cambridge,Brentford,10000+ employees,1830,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0,62000,119000,90500.0,0
887,887,Senior Data Scientist,119-187,At Factual we love all things data! Our missio...,4.3,Factual,Los Angeles,Los Angeles,51 to 200 employees,2008,...,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,Foursquare,0,0,119000,187000,153000.0,1
892,892,Jr. Data Scientist,81-132,MITRE\nis a trusted operator of federally fund...,3.2,MITRE,McLean,Bedford,5001 to 10000 employees,1958,...,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0,81000,132000,106500.0,0
893,893,Senior Data Scientist,120-140,"SkySync is a dynamic, fast-paced, venture-back...",5.0,SkySync,Ann Arbor,Ann Arbor,51 to 200 employees,2011,...,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,1,120000,140000,130000.0,1
895,895,Products Data Analyst II,90-157,TriNet is a leading provider of comprehensive ...,3.3,TriNet,Dublin,Dublin,1001 to 5000 employees,1988,...,Consulting,Business Services,$2 to $5 billion (USD),"Paychex, Insperity, ADP",0,0,90000,157000,123500.0,1
896,896,Data Architect / Data Modeler,63-110,Medidata: Conquering Diseases Together\n\nMedi...,4.3,Medidata Solutions,New York,New York,1001 to 5000 employees,1999,...,Enterprise Software & Network Solutions,Information Technology,$500 million to $1 billion (USD),Oracle,0,0,63000,110000,86500.0,1
897,897,Analytics Manager - Data Mart,42-86,We have an opportunity to join the Alliance as...,3.5,Central California Alliance for Health,Scotts Valley,Scotts Valley,501 to 1000 employees,1996,...,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,42000,86000,64000.0,1
898,898,Lead Data Analyst,32-62,JOB DESCRIPTION:\n\nSignpost is looking for a ...,3.9,Signpost,New York,New York,201 to 500 employees,2010,...,Internet,Information Technology,$10 to $25 million (USD),-1,0,0,32000,62000,47000.0,1
899,899,Data Science Engineer - Mobile,116-208,Mobile is a top strategic priority for Adobe. ...,4.0,Adobe,San Jose,San Jose,10000+ employees,1982,...,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),"Apple, Microsoft",0,0,116000,208000,162000.0,1
900,900,Senior Data Scientist Oncology,107-173,At AstraZeneca we are constantly pushing the b...,3.9,AstraZeneca,Gaithersburg,Cambridge,10000+ employees,1913,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0,107000,173000,140000.0,0
901,901,Data Scientist,65-113,DatamanUSA has an exciting opportunity for a D...,3.4,"DatamanUSA, LLC",Olympia,Centennial,51 to 200 employees,-1,...,IT Services,Information Technology,$5 to $10 million (USD),-1,0,0,65000,113000,89000.0,0
902,902,Sr. Data Engineer - Contract-to-Hire (Java),69-127,As we strive to make a better day for our gues...,3.0,Pilot Flying J Travel Centers LLC,Knoxville,Knoxville,10000+ employees,1958,...,Gas Stations,Retail,$10+ billion (USD),"TravelCenters of America, Love's Travel Stops ...",0,0,69000,127000,98000.0,1
904,904,Senior Data Scientist - R&D Oncology,102-172,"At AstraZeneca,we work together to deliver inn...",3.9,AstraZeneca,New York,Cambridge,10000+ employees,1913,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Roche, GlaxoSmithKline, Novartis",0,0,102000,172000,137000.0,0
907,907,Data Engineer,74-124,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance,Denver,Denver,501 to 1000 employees,1915,...,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,74000,124000,99000.0,1
909,909,Food Scientist - Developer,40-68,Palermo Villa Inc. is interested in a high-ene...,3.3,Palermo's Pizza,Milwaukee,Milwaukee,501 to 1000 employees,1964,...,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,-1,0,0,40000,68000,54000.0,1
910,910,Senior Data Engineer,76-142,Sr. Data Engineer FTE for Franklin\n\nThere ar...,3.2,Equian LLC,Franklin,Indianapolis,1001 to 5000 employees,2004,...,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,0,0,76000,142000,109000.0,0
911,911,Data Engineer,76-142,MetroStar Systems is looking for a Data Engine...,3.4,MetroStar Systems,Rockville,Reston,201 to 500 employees,1999,...,IT Services,Information Technology,$25 to $50 million (USD),-1,0,0,76000,142000,109000.0,0
912,912,Senior Data Scientist,108-171,"The Infrastructure, Architecture, and Tools te...",4.4,MathWorks,Natick,Natick,1001 to 5000 employees,1984,...,Computer Hardware & Software,Information Technology,$1 to $2 billion (USD),-1,0,0,108000,171000,139500.0,1
913,913,"Director II, Data Science - GRM Actuarial",202-306,Advance your career at Liberty Mutual Insuranc...,3.3,Liberty Mutual Insurance,Chicago,Boston,10000+ employees,1912,...,Insurance Carriers,Insurance,$10+ billion (USD),"Travelers, Allstate, State Farm",0,0,202000,306000,254000.0,0
914,914,Machine Learning Engineer,91-159,We are seeking a highly-experienced ML Enginee...,3.2,Information Builders,New York,New York,1001 to 5000 employees,1975,...,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Qlik, Tableau Software, Informatica",0,0,91000,159000,125000.0,1
916,916,"Sr Expert Data Science, Advanced Visual Analyt...",80-133,"Posting Title\nSr Expert Data Science, Advance...",3.8,Novartis,Cambridge,Basel,10000+ employees,1996,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,80000,133000,106500.0,0
919,919,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,21-34,Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare,Millville,Lewes,1001 to 5000 employees,1935,...,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0,21000,34000,27500.0,0
920,920,"Scientist, Molecular/Cellular Biologist",49-97,"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics,South San Francisco,San Francisco,201 to 500 employees,2012,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,...",0,0,49000,97000,73000.0,0
921,921,Staff Scientist-Downstream Process Development,49-113,ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories,Rockville,Rockville,201 to 500 employees,1961,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1,0,0,49000,113000,81000.0,1
924,924,Data Scientist,96-161,SummaryProvide data management and statistical...,3.2,"Numeric, LLC",Philadelphia,Chadds Ford,1 to 50 employees,-1,...,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,96000,161000,128500.0,0
926,926,Scientist - Analytical Services,65-134,British American Tobacco\nReynolds American In...,3.1,Reynolds American,Winston-Salem,Winston-Salem,5001 to 10000 employees,1875,...,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0,65000,134000,99500.0,1
928,928,"Associate Scientist / Sr. Associate Scientist,...",59-125,"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe,South San Francisco,Sunnyvale,501 to 1000 employees,2006,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat...",0,0,59000,125000,92000.0,0
929,929,Associate Data Analyst- Graduate Development P...,32-59,Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate,Richfield,Richfield,501 to 1000 employees,1989,...,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,32000,59000,45500.0,1
930,930,Sr. Data Engineer,87-158,Join our team of Data Consultants and work on ...,4.5,Moser Consulting,Indianapolis,Indianapolis,51 to 200 employees,1996,...,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,87000,158000,122500.0,1
931,931,Clinical Data Analyst,27-48,Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health,Tampa,Tampa,1001 to 5000 employees,1977,...,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth",0,0,27000,48000,37500.0,1
932,932,IT Associate Data Analyst,39-69,"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group,Worcester,Worcester,5001 to 10000 employees,1852,...,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,39000,69000,54000.0,1
933,933,Business Data Analyst,36-71,(We are unable to sponsor for this role now or...,3.8,Fareportal,New York,New York,1001 to 5000 employees,2002,...,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",0,0,36000,71000,53500.0,1
934,934,Senior Insurance Data Scientist,107-173,"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion,Chicago,Chicago,5001 to 10000 employees,1968,...,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1,0,0,107000,173000,140000.0,1
935,935,Senior Data Science Systems Engineer,56-99,"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE,Hampton,Bedford,5001 to 10000 employees,1958,...,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0,56000,99000,77500.0,0
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,25-28,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates,Cambridge,Cambridge,1 to 50 employees,1976,...,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1,1,1,25000,28000,26500.0,1
938,938,Senior Scientist - Regulatory Submissions,80-155,British American Tobacco\nReynolds American In...,3.1,Reynolds American,Winston-Salem,Winston-Salem,5001 to 10000 employees,1875,...,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0,80000,155000,117500.0,1
939,939,Scientist - Biomarker and Flow Cytometry,43-98,"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience,San Diego,San Diego,501 to 1000 employees,2006,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1,0,0,43000,98000,70500.0,1
940,940,Revenue Analytics Manager,45-78,HOVER uses patented technology making it possi...,4.8,HOVER,San Francisco,San Francisco,51 to 200 employees,2011,...,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1,0,0,45000,78000,61500.0,1
941,941,Sr. Scientist Method Development,50-110,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions,Marietta,Morrisville,1001 to 5000 employees,2015,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0,50000,110000,80000.0,0
942,942,"Associate Scientist, LC/MS Biologics",44-96,Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions,Ithaca,Morrisville,1001 to 5000 employees,2015,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0,44000,96000,70000.0,0
943,943,"Research Scientist, Immunology - Cancer Biology",100-140,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos,Cambridge,San Mateo,Unknown,-1,...,-1,-1,Unknown / Non-Applicable,-1,0,1,100000,140000,120000.0,0
944,944,IT - Data Engineer II,61-119,IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance,Quincy,Quincy,1001 to 5000 employees,1988,...,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,61000,119000,90000.0,1
945,945,Machine Learning Engineer (NLP),80-142,CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation,Palo Alto,Palo Alto,1 to 50 employees,2007,...,K-12 Education,Education,Unknown / Non-Applicable,-1,0,0,80000,142000,111000.0,1
946,946,Senior Data Analyst,99-178,Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360,San Francisco,San Francisco,51 to 200 employees,2008,...,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,0,99000,178000,138500.0,1
947,947,Data Science Project Manager,37-100,"At MassMutual, we are passionate about helping...",3.6,MassMutual,Boston,Springfield,5001 to 10000 employees,1851,...,Insurance Carriers,Insurance,$10+ billion (USD),-1,0,0,37000,100000,68500.0,0
948,948,Data Engineer,62-113,Do you find data architecture exciting? Does b...,3.9,Fivestars,San Francisco,San Francisco,201 to 500 employees,2011,...,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0,0,62000,113000,87500.0,1
949,949,"Principal, Data Science - Advanced Analytics",86-137,IQVIA is the leading human data science compan...,3.6,IQVIA,Plymouth Meeting,Durham,10000+ employees,2017,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0,0,86000,137000,111500.0,0
950,950,"Sr Scientist, Immuno-Oncology - Oncology",58-111,Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK,Cambridge,Brentford,10000+ employees,1830,...,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0,58000,111000,84500.0,0
951,951,Senior Data Engineer,72-133,THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite,Nashville,San Francisco,1001 to 5000 employees,2006,...,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0,72000,133000,102500.0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",56-91,The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute,Pittsburgh,Pittsburgh,501 to 1000 employees,1984,...,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0,56000,91000,73500.0,1
953,953,Data Science Manager,95-160,Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC",Allentown,Chadds Ford,1 to 50 employees,-1,...,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,95000,160000,127500.0,0
955,955,Research Scientist – Security and Privacy,61-126,Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute,Beavercreek,Arlington,501 to 1000 employees,1967,...,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0,61000,126000,93500.0,0

#### Create a new column 'Company age' to show age of the company

In [48]:
df_modified["company_age"] = [x if x<0 else 2022-x for x in df_modified["Founded"]]

<ipython-input-48-7dc2f08728b1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["company_age"] = [x if x<0 else 2022-x for x in df_modified["Founded"]]

In [49]:
df_modified.head(50)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,...,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53000,91000,72000.0,0,49
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,...,Health Care,$2 to $5 billion (USD),-1,0,0,63000,112000,87500.0,0,38
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,Business Services,$100 to $500 million (USD),-1,0,0,80000,90000,85000.0,1,12
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0,1,57
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,...,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0,1,24
5,5,Data Scientist,71-119,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,...,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71000,119000,95000.0,1,22
6,6,Data Scientist,54-93,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,...,Finance,Unknown / Non-Applicable,-1,0,0,54000,93000,73500.0,1,14
7,7,Data Scientist,86-142,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20,San Jose,Seattle,201 to 500 employees,2005,...,Business Services,$25 to $50 million (USD),-1,0,0,86000,142000,114000.0,0,17
8,8,Research Scientist,38-84,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health,Rochester,Rochester,10000+ employees,2014,...,Health Care,$500 million to $1 billion (USD),-1,0,0,38000,84000,61000.0,1,8
9,9,Data Scientist,120-160,isn’t your usual company. Our work is powered ...,4.6,<intent>,New York,New York,51 to 200 employees,2009,...,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120000,160000,140000.0,1,13
10,10,Data Scientist,126-201,"At Wish, our Data Science & Engineering team i...",3.5,Wish,San Jose,San Francisco,501 to 1000 employees,2011,...,Retail,$1 to $2 billion (USD),-1,0,0,126000,201000,163500.0,0,11
11,11,Data Scientist,64-106,"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech,Chantilly,Herndon,5001 to 10000 employees,1968,...,Business Services,$1 to $2 billion (USD),-1,0,0,64000,106000,85000.0,0,54
12,12,Staff Data Scientist - Technology,106-172,Position Summary...\nDrives the execution of m...,3.2,Walmart,Plano,Bentonville,10000+ employees,1962,...,Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106000,172000,139000.0,0,60
13,13,Data Analyst,46-85,"Are you an experienced Data Analyst, skilled a...",4.1,Yesler,Seattle,Seattle,201 to 500 employees,2012,...,Business Services,Unknown / Non-Applicable,-1,0,0,46000,85000,65500.0,1,10
14,14,Data Scientist,83-144,Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals,Cambridge,OSAKA,10000+ employees,1781,...,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83000,144000,113500.0,0,241
15,15,Data Engineer I,102-190,This opportunity is within Audibles Data Engin...,3.6,Audible,Newark,Newark,1001 to 5000 employees,1995,...,Media,Unknown / Non-Applicable,-1,0,0,102000,190000,146000.0,1,27
16,16,"Scientist I/II, Biology",67-137,"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines,Cambridge,Cambridge,51 to 200 employees,2011,...,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67000,137000,102000.0,1,11
17,17,Customer Data Scientist,118-189,Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai,Mountain View,Mountain View,201 to 500 employees,2011,...,Information Technology,Unknown / Non-Applicable,-1,0,0,118000,189000,153500.0,1,11
18,18,Data Scientist - Health Data Analytics,110-175,"At Nuna, our mission is to make high-quality h...",4.2,Nuna,San Francisco,San Francisco,51 to 200 employees,2010,...,Information Technology,Unknown / Non-Applicable,-1,0,0,110000,175000,142500.0,1,12
19,19,Data Scientist,64-111,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance,Denver,Denver,501 to 1000 employees,1915,...,Insurance,$500 million to $1 billion (USD),-1,0,0,64000,111000,87500.0,1,107
20,20,Data Scientist,81-130,About Our Team\n\nWe understand that the first...,3.2,Porch,Seattle,Seattle,201 to 500 employees,2012,...,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81000,130000,105500.0,1,10
21,21,Senior Data Scientist / Machine Learning,73-119,IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ,Dallas,Mountain View,201 to 500 employees,2013,...,Insurance,Unknown / Non-Applicable,-1,0,0,73000,119000,96000.0,0,9
22,22,Data Scientist - Quantitative,86-139,Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com,Chicago,New Plymouth,501 to 1000 employees,1995,...,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86000,139000,112500.0,0,27
23,23,Data Scientist,63-105,Position Summary\nOur Data Science team is cur...,4.3,SMC 3,Louisville,Peachtree City,51 to 200 employees,1935,...,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63000,105000,84000.0,0,87
25,25,Data Scientist,109-177,Are you passionate about solving challenging p...,4.0,Novetta,Herndon,Mc Lean,501 to 1000 employees,2012,...,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109000,177000,143000.0,0,10
26,26,Digital Health Data Scientist,63-110,ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer,Cambridge,New York,10000+ employees,1849,...,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63000,110000,86500.0,0,173
27,27,Data Scientist,75-124,As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union,Hillsboro,San Jose,1001 to 5000 employees,1952,...,Finance,$100 to $500 million (USD),-1,0,0,75000,124000,99500.0,0,70
28,28,Associate Data Analyst,34-61,"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group,Worcester,Worcester,5001 to 10000 employees,1852,...,Insurance,$5 to $10 billion (USD),-1,0,0,34000,61000,47500.0,1,170
29,29,Clinical Data Scientist,63-105,THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer,Groton,New York,10000+ employees,1849,...,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63000,105000,84000.0,0,173
30,30,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,Business Services,$100 to $500 million (USD),-1,0,0,80000,90000,85000.0,1,12
31,31,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0,1,57
32,32,Data Scientist,72-120,Preferred Qualifications\nMasters degree or do...,3.6,Amrock,Detroit,Detroit,1001 to 5000 employees,1997,...,Real Estate,$500 million to $1 billion (USD),-1,0,0,72000,120000,96000.0,1,25
33,33,Data Scientist / Machine Learning Expert,86-143,Posting Title\nData Scientist / Machine Learni...,3.8,Novartis,Cambridge,Basel,10000+ employees,1996,...,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,86000,143000,114500.0,0,26
34,34,Data Scientist,93-149,"Title: Software Engineer, Data Science\n\nDesi...",3.8,Juniper Networks,Sunnyvale,Sunnyvale,5001 to 10000 employees,1996,...,Telecommunications,$2 to $5 billion (USD),-1,0,0,93000,149000,121000.0,1,26
35,35,Data Scientist,85-140,New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs,Ipswich,Ipswich,201 to 500 employees,1974,...,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Thermo Fisher Scientific, Enzymatics, Illumina",0,0,85000,140000,112500.0,1,48
36,36,Web Data Analyst,77-135,We are looking for a Web Data Analyst to assis...,4.2,Clarity Insights,San Jose,Chicago,201 to 500 employees,2008,...,Information Technology,Unknown / Non-Applicable,-1,0,0,77000,135000,106000.0,0,14
37,37,Data Scientist,82-132,Overview\n\n\nAre you passionate about changin...,3.5,Esri,Redlands,Redlands,1001 to 5000 employees,1969,...,Information Technology,$1 to $2 billion (USD),Pitney Bowes,0,0,82000,132000,107000.0,1,53
38,38,Data Scientist,83-137,STR is a government research contractor specia...,4.7,Systems & Technology Research,Woburn,Woburn,201 to 500 employees,2010,...,Aerospace & Defense,$100 to $500 million (USD),-1,0,0,83000,137000,110000.0,1,12
39,39,Senior Data Scientist,115-180,"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius,Fremont,Gottingen,5001 to 10000 employees,1870,...,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1,0,0,115000,180000,147500.0,0,152
40,40,Data Engineer,74-138,Lancer Insurance Company is looking for a Data...,3.5,Lancer Insurance,Long Beach,Long Beach,201 to 500 employees,1985,...,Insurance,$100 to $500 million (USD),-1,0,0,74000,138000,106000.0,1,37
41,41,Data Analyst,64-112,About the Role:\n\nThe Data Analyst plays a cr...,4.2,Sauce Labs,San Francisco,San Francisco,201 to 500 employees,2008,...,Information Technology,$50 to $100 million (USD),"BrowserStack, Selenium Master, Perfecto Mobile",0,0,64000,112000,88000.0,1,14
43,43,Data Engineer,68-129,Position Title: Data Engineer\n\nPersivia is s...,3.6,Persivia,Marlborough,Lowell,1 to 50 employees,-1,...,-1,Less than $1 million (USD),-1,0,0,68000,129000,98500.0,0,-1
44,44,Data Scientist - Algorithms & Inference,110-175,"At Nuna, our mission is to make high-quality h...",4.2,Nuna,San Francisco,San Francisco,51 to 200 employees,2010,...,Information Technology,Unknown / Non-Applicable,-1,0,0,110000,175000,142500.0,1,12
45,45,Scientist,52-113,"We are a global team of 6000 visionaries, doer...",3.4,Edgewell Personal Care,Allendale,Shelton,5001 to 10000 employees,2015,...,Manufacturing,$2 to $5 billion (USD),"Unilever, Procter & Gamble, Henkel",0,0,52000,113000,82500.0,0,7
46,46,Senior Data Scientist,110-150,"Working for Equity Residential (EQR), a leadin...",4.3,Equity Residential,Chicago,Chicago,1001 to 5000 employees,1993,...,Real Estate,$2 to $5 billion (USD),"UDR, AvalonBay Communities, Essex Property Trust",0,0,110000,150000,130000.0,1,29
48,48,Data Scientist,150-160,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services,Washington,Alexandria,Unknown,-1,...,Information Technology,Unknown / Non-Applicable,-1,0,1,150000,160000,155000.0,0,-1
49,49,Lead Data Scientist,158-211,As the world's leader in digital payments tech...,3.7,Visa Inc.,Bellevue,Foster City,10000+ employees,1958,...,Information Technology,$10+ billion (USD),"American Express, Mastercard, Discover",0,0,158000,211000,184500.0,0,64
50,50,Associate Data Analyst,20-39,Intrado is looking for an Associate Data Analy...,3.1,Intrado,Longmont,Omaha,5001 to 10000 employees,1986,...,Information Technology,$2 to $5 billion (USD),-1,0,0,20000,39000,29500.0,0,36
51,51,Spectral Scientist/Engineer,56-117,Thank you for your interest in joining the Cen...,4.7,Centauri,Beavercreek,Chantilly,501 to 1000 employees,1999,...,Aerospace & Defense,$100 to $500 million (USD),"TASC, Vencore, Booz Allen Hamilton",0,0,56000,117000,86500.0,0,23
52,52,College Hire - Data Scientist - Open to Decemb...,63-99,Description\n\nCaterpillar's legacy of industr...,3.7,Caterpillar,Peoria,Deerfield,10000+ employees,1925,...,Manufacturing,$10+ billion (USD),"John Deere, Komatsu, CNH Industrial",0,0,63000,99000,81000.0,0,97

#### Indicate 'None' if a company has no competitors else the competitor name

In [50]:
df_modified["Competitors"] = ["None" if x=='-1' else x for x in df_modified["Competitors"]]

<ipython-input-50-fa849602ab2d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Competitors"] = ["None" if x=='-1' else x for x in df_modified["Competitors"]]

In [51]:
df_modified.head(10)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age
0,0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,...,Aerospace & Defense,$50 to $100 million (USD),None,0,0,53000,91000,72000.0,0,49
1,1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,...,Health Care,$2 to $5 billion (USD),None,0,0,63000,112000,87500.0,0,38
2,2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,Business Services,$100 to $500 million (USD),None,0,0,80000,90000,85000.0,1,12
3,3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0,1,57
4,4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,...,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0,1,24
5,5,Data Scientist,71-119,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,...,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71000,119000,95000.0,1,22
6,6,Data Scientist,54-93,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,...,Finance,Unknown / Non-Applicable,None,0,0,54000,93000,73500.0,1,14
7,7,Data Scientist,86-142,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20,San Jose,Seattle,201 to 500 employees,2005,...,Business Services,$25 to $50 million (USD),None,0,0,86000,142000,114000.0,0,17
8,8,Research Scientist,38-84,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health,Rochester,Rochester,10000+ employees,2014,...,Health Care,$500 million to $1 billion (USD),None,0,0,38000,84000,61000.0,1,8
9,9,Data Scientist,120-160,isn’t your usual company. Our work is powered ...,4.6,<intent>,New York,New York,51 to 200 employees,2009,...,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120000,160000,140000.0,1,13

#### Add 'K' in the Salary Estimate column to represent *1000

In [52]:
df_modified["Salary Estimate"] = df["Salary Estimate"].apply(lambda x: x+'K')

<ipython-input-52-b4bc50215f48>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Salary Estimate"] = df["Salary Estimate"].apply(lambda x: x+'K')

In [53]:
df_modified.head(5)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age
0,0,Data Scientist,$53K-$91K (Glassdoor est.)K,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,...,Aerospace & Defense,$50 to $100 million (USD),None,0,0,53000,91000,72000.0,0,49
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.)K,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,...,Health Care,$2 to $5 billion (USD),None,0,0,63000,112000,87500.0,0,38
2,2,Data Scientist,$80K-$90K (Glassdoor est.)K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,Business Services,$100 to $500 million (USD),None,0,0,80000,90000,85000.0,1,12
3,3,Data Scientist,$56K-$97K (Glassdoor est.)K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0,1,57
4,4,Data Scientist,$86K-$143K (Glassdoor est.)K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,...,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0,1,24

#### Remove 'Glassdoor est.' from the Salary Estimate column

In [54]:
df_modified["Salary Estimate"] = [x.split('(')[0] for x in df_modified["Salary Estimate"]]

<ipython-input-54-7f7a50946bc5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Salary Estimate"] = [x.split('(')[0] for x in df_modified["Salary Estimate"]]

In [55]:
df_modified.head(10)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,hourly,employer provided,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age
0,0,Data Scientist,$53K-$91K,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,...,Aerospace & Defense,$50 to $100 million (USD),None,0,0,53000,91000,72000.0,0,49
1,1,Healthcare Data Scientist,$63K-$112K,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,...,Health Care,$2 to $5 billion (USD),None,0,0,63000,112000,87500.0,0,38
2,2,Data Scientist,$80K-$90K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,Business Services,$100 to $500 million (USD),None,0,0,80000,90000,85000.0,1,12
3,3,Data Scientist,$56K-$97K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56000,97000,76500.0,1,57
4,4,Data Scientist,$86K-$143K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,...,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86000,143000,114500.0,1,24
5,5,Data Scientist,$71K-$119K,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,...,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71000,119000,95000.0,1,22
6,6,Data Scientist,$54K-$93K,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,...,Finance,Unknown / Non-Applicable,None,0,0,54000,93000,73500.0,1,14
7,7,Data Scientist,$86K-$142K,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20,San Jose,Seattle,201 to 500 employees,2005,...,Business Services,$25 to $50 million (USD),None,0,0,86000,142000,114000.0,0,17
8,8,Research Scientist,$38K-$84K,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health,Rochester,Rochester,10000+ employees,2014,...,Health Care,$500 million to $1 billion (USD),None,0,0,38000,84000,61000.0,1,8
9,9,Data Scientist,$120K-$160K,isn’t your usual company. Our work is powered ...,4.6,<intent>,New York,New York,51 to 200 employees,2009,...,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120000,160000,140000.0,1,13

#### Display the 2nd job description in the Job Desription column

In [56]:
df_modified['Job Description'][1]

'What You Will Do:\n\nI. General Summary\n\nThe Healthcare Data Scientist position will join our Advanced Analytics group at the University of Maryland Medical System (UMMS) in support of its strategic priority to become a data-driven and outcomes-oriented organization. The successful candidate will have 3+ years of experience with Machine Learning, Predictive Modeling, Statistical Analysis, Mathematical Optimization, Algorithm Development and a passion for working with healthcare data. Previous experience with various computational approaches along with an ability to demonstrate a portfolio of relevant prior projects is essential. This position will report to the UMMS Vice President for Enterprise Data and Analytics (ED&A).\n\nII. Principal Responsibilities and Tasks\n\n• Develops predictive and prescriptive analytic models in support of the organization’s clinical, operations and business initiatives and priorities.\n• Deploys solutions so that they provide actionable insights to the organization and are embedded or integrated with application systems\n• Supports and drives analytic efforts designed around organization’s strategic priorities and clinical/business problems\n• Works in a team to drive disruptive innovation, which may translate into improved quality of care, clinical outcomes, reduced costs, temporal efficiencies and process improvements.\n• Builds and extends our analytics portfolio supported by robust documentation\n• Works with autonomy to find solutions to complex problems using open source tools and in-house development\n• Stays abreast of state-of-the-art literature in the fields of operations research, statistical modeling, statistical process control and mathematical optimization\n• Creates, communicates, and manages the project plans and other required project documentation and provides updates to leadership as necessary\n• Develops and maintains relationships with business, IT and clinical leaders and stakeholders across the enterprise to facilitate collaboration and effective communication\n• Works with the analytics team and clinical/business stakeholders to develop pilots so that they may be tested and validated in pilot settings\n• Performs analysis to evaluate primary and secondary objectives from such pilots\n• Assists leadership with strategies for scaling successful projects across the organization and enhances the analytics applications based on feedback from end-users and clinical/business consumers\n• Assists leadership with dissemination of success stories (and failures) in an effort to increase analytics literacy and adoption across the organization.\n\nWhat You Need to Be Successful:\n\nIII. Education and Experience\n\n• Master’s or higher degree (may be substituted by relevant work experience) in applied mathematics, physics, computer science, engineering, statistics or a related field\n• 3+ years of Mathematical Optimization, Machine Learning, Predictive Analytics and Algorithm Development experience (experience with tools such as WEKA, RapidMiner, R. Python or other open source tools strongly desired)\n• Strong development skills in two or more of the following: C/C++, C#, Python, Java\n• Combining analytic methods with advanced data visualizations\n• Expert ability to breakdown and clearly define problems\n• Experience with Natural Language Processing preferred\n\nIV. Knowledge, Skills and Abilities\n\n• Proven communications skills – Effective at working independently and in collaboration with other staff members. Capable of clearly presenting findings orally, in writing, or through graphics.\n• Proven analytical skills – Able to compare, contrast, and validate work with keen attention to detail. Skilled in working with “real world” data including scrubbing, transformation, and imputation.\n• Proven problem solving skills – Able to plan work, set clear direction, and coordinate own tasks in a fast-paced multidisciplinary environment. Expert at triaging issues, identifying data anomalies, and debugging software.\n• Design and prototype new application functionality for our products.\n• Change oriented – actively generates process improvements; supports and drives change, and confronts difficult circumstances in creative ways\n• Effective communicator and change agent\n• Ability to prioritize the tasks of the project timeline to achieve the desired results\n• Strong analytic and problem solving skills\n• Ability to cooperatively and effectively work with people from various organization levels\n\nWe are an Equal Opportunity Employer and do not discriminate against any employee or applicant for employment because of race, color, sex, age, national origin, religion, sexual orientation, gender identity, status as a veteran, and basis of disability or any other federal, state or local protected class.'

#### Create new columns showing the most prevalent skills sort after in the Job Desription

In [57]:
df_modified["Python"] = [1 if 'python' in x.lower() else 0 for x in df_modified["Job Description"]]
#df_modified["R"] = [1 if 'r-studio' or 'r studio' in x.lower() else 0 for x in df_modified["Job Description"]]
df_modified["R"]= [1 if 'r-studio' in x.lower() else 0 for x in df_modified["Job Description"]]
df_modified["Excel"]= [1 if 'excel' in x.lower() else 0 for x in df_modified["Job Description"]]
df_modified["aws"]= [1 if 'aws' in x.lower() else 0 for x in df_modified["Job Description"]]
df_modified['Spark']= [1 if 'spark' in x.lower() else 0 for x in df_modified["Job Description"]]

<ipython-input-57-85214644cc59>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Python"] = [1 if 'python' in x.lower() else 0 for x in df_modified["Job Description"]]
<ipython-input-57-85214644cc59>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["R"]= [1 if 'r-studio' in x.lower() else 0 for x in df_modified["Job Description"]]
<ipython-input-57-85214644cc59>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["Excel"]= [1 if 'excel' in x.lower() else 0 for x in df_modified["Job Description"]]
<ipython-input-57-85214644cc59>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified["aws"]= [1 if 'aws' in x.lower() else 0 for x in df_modified["Job Description"]]
<ipython-input-57-85214644cc59>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_modified['Spark']= [1 if 'spark' in x.lower() else 0 for x in df_modified["Job Description"]]

In [58]:
df_modified.head(60)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age,Python,R,Excel,aws,Spark
0,0,Data Scientist,$53K-$91K,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,...,53000,91000,72000.0,0,49,1,0,1,0,0
1,1,Healthcare Data Scientist,$63K-$112K,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,...,63000,112000,87500.0,0,38,1,0,0,0,0
2,2,Data Scientist,$80K-$90K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,80000,90000,85000.0,1,12,1,0,1,0,1
3,3,Data Scientist,$56K-$97K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,56000,97000,76500.0,1,57,1,0,0,0,0
4,4,Data Scientist,$86K-$143K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,...,86000,143000,114500.0,1,24,1,0,1,0,0
5,5,Data Scientist,$71K-$119K,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,...,71000,119000,95000.0,1,22,1,0,1,1,0
6,6,Data Scientist,$54K-$93K,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,...,54000,93000,73500.0,1,14,0,0,1,0,0
7,7,Data Scientist,$86K-$142K,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20,San Jose,Seattle,201 to 500 employees,2005,...,86000,142000,114000.0,0,17,1,0,1,1,1
8,8,Research Scientist,$38K-$84K,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health,Rochester,Rochester,10000+ employees,2014,...,38000,84000,61000.0,1,8,0,0,0,0,0
9,9,Data Scientist,$120K-$160K,isn’t your usual company. Our work is powered ...,4.6,<intent>,New York,New York,51 to 200 employees,2009,...,120000,160000,140000.0,1,13,1,0,0,0,1
10,10,Data Scientist,$126K-$201K,"At Wish, our Data Science & Engineering team i...",3.5,Wish,San Jose,San Francisco,501 to 1000 employees,2011,...,126000,201000,163500.0,0,11,1,0,0,0,0
11,11,Data Scientist,$64K-$106K,"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech,Chantilly,Herndon,5001 to 10000 employees,1968,...,64000,106000,85000.0,0,54,0,0,0,0,0
12,12,Staff Data Scientist - Technology,$106K-$172K,Position Summary...\nDrives the execution of m...,3.2,Walmart,Plano,Bentonville,10000+ employees,1962,...,106000,172000,139000.0,0,60,0,0,0,0,0
13,13,Data Analyst,$46K-$85K,"Are you an experienced Data Analyst, skilled a...",4.1,Yesler,Seattle,Seattle,201 to 500 employees,2012,...,46000,85000,65500.0,1,10,1,0,1,1,1
14,14,Data Scientist,$83K-$144K,Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals,Cambridge,OSAKA,10000+ employees,1781,...,83000,144000,113500.0,0,241,1,0,0,0,1
15,15,Data Engineer I,$102K-$190K,This opportunity is within Audibles Data Engin...,3.6,Audible,Newark,Newark,1001 to 5000 employees,1995,...,102000,190000,146000.0,1,27,0,0,1,0,0
16,16,"Scientist I/II, Biology",$67K-$137K,"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines,Cambridge,Cambridge,51 to 200 employees,2011,...,67000,137000,102000.0,1,11,0,0,1,0,0
17,17,Customer Data Scientist,$118K-$189K,Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai,Mountain View,Mountain View,201 to 500 employees,2011,...,118000,189000,153500.0,1,11,1,0,1,1,1
18,18,Data Scientist - Health Data Analytics,$110K-$175K,"At Nuna, our mission is to make high-quality h...",4.2,Nuna,San Francisco,San Francisco,51 to 200 employees,2010,...,110000,175000,142500.0,1,12,0,0,0,0,0
19,19,Data Scientist,$64K-$111K,"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance,Denver,Denver,501 to 1000 employees,1915,...,64000,111000,87500.0,1,107,1,0,1,0,0
20,20,Data Scientist,$81K-$130K,About Our Team\n\nWe understand that the first...,3.2,Porch,Seattle,Seattle,201 to 500 employees,2012,...,81000,130000,105500.0,1,10,1,0,0,0,1
21,21,Senior Data Scientist / Machine Learning,$73K-$119K,IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ,Dallas,Mountain View,201 to 500 employees,2013,...,73000,119000,96000.0,0,9,0,0,1,0,0
22,22,Data Scientist - Quantitative,$86K-$139K,Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com,Chicago,New Plymouth,501 to 1000 employees,1995,...,86000,139000,112500.0,0,27,1,0,1,1,0
23,23,Data Scientist,$63K-$105K,Position Summary\nOur Data Science team is cur...,4.3,SMC 3,Louisville,Peachtree City,51 to 200 employees,1935,...,63000,105000,84000.0,0,87,1,0,1,0,0
25,25,Data Scientist,$109K-$177K,Are you passionate about solving challenging p...,4.0,Novetta,Herndon,Mc Lean,501 to 1000 employees,2012,...,109000,177000,143000.0,0,10,1,0,0,1,0
26,26,Digital Health Data Scientist,$63K-$110K,ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer,Cambridge,New York,10000+ employees,1849,...,63000,110000,86500.0,0,173,1,0,1,1,0
27,27,Data Scientist,$75K-$124K,As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union,Hillsboro,San Jose,1001 to 5000 employees,1952,...,75000,124000,99500.0,0,70,1,0,1,1,1
28,28,Associate Data Analyst,$34K-$61K,"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group,Worcester,Worcester,5001 to 10000 employees,1852,...,34000,61000,47500.0,1,170,0,0,1,0,0
29,29,Clinical Data Scientist,$63K-$105K,THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer,Groton,New York,10000+ employees,1849,...,63000,105000,84000.0,0,173,0,0,1,1,0
30,30,Data Scientist,$80K-$90K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,...,80000,90000,85000.0,1,12,1,0,1,0,1
31,31,Data Scientist,$56K-$97K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,...,56000,97000,76500.0,1,57,1,0,0,0,0
32,32,Data Scientist,$72K-$120K,Preferred Qualifications\nMasters degree or do...,3.6,Amrock,Detroit,Detroit,1001 to 5000 employees,1997,...,72000,120000,96000.0,1,25,1,0,0,0,0
33,33,Data Scientist / Machine Learning Expert,$86K-$143K,Posting Title\nData Scientist / Machine Learni...,3.8,Novartis,Cambridge,Basel,10000+ employees,1996,...,86000,143000,114500.0,0,26,1,0,0,0,0
34,34,Data Scientist,$93K-$149K,"Title: Software Engineer, Data Science\n\nDesi...",3.8,Juniper Networks,Sunnyvale,Sunnyvale,5001 to 10000 employees,1996,...,93000,149000,121000.0,1,26,1,0,1,0,1
35,35,Data Scientist,$85K-$140K,New England Biolabs is seeking a Data Scientis...,4.7,New England Biolabs,Ipswich,Ipswich,201 to 500 employees,1974,...,85000,140000,112500.0,1,48,1,0,1,0,0
36,36,Web Data Analyst,$77K-$135K,We are looking for a Web Data Analyst to assis...,4.2,Clarity Insights,San Jose,Chicago,201 to 500 employees,2008,...,77000,135000,106000.0,0,14,1,0,1,0,0
37,37,Data Scientist,$82K-$132K,Overview\n\n\nAre you passionate about changin...,3.5,Esri,Redlands,Redlands,1001 to 5000 employees,1969,...,82000,132000,107000.0,1,53,1,0,0,1,1
38,38,Data Scientist,$83K-$137K,STR is a government research contractor specia...,4.7,Systems & Technology Research,Woburn,Woburn,201 to 500 employees,2010,...,83000,137000,110000.0,1,12,1,0,1,0,1
39,39,Senior Data Scientist,$115K-$180K,"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius,Fremont,Gottingen,5001 to 10000 employees,1870,...,115000,180000,147500.0,0,152,1,0,1,0,0
40,40,Data Engineer,$74K-$138K,Lancer Insurance Company is looking for a Data...,3.5,Lancer Insurance,Long Beach,Long Beach,201 to 500 employees,1985,...,74000,138000,106000.0,1,37,1,0,1,0,0
41,41,Data Analyst,$64K-$112K,About the Role:\n\nThe Data Analyst plays a cr...,4.2,Sauce Labs,San Francisco,San Francisco,201 to 500 employees,2008,...,64000,112000,88000.0,1,14,1,0,1,1,0
43,43,Data Engineer,$68K-$129K,Position Title: Data Engineer\n\nPersivia is s...,3.6,Persivia,Marlborough,Lowell,1 to 50 employees,-1,...,68000,129000,98500.0,0,-1,0,0,1,0,0
44,44,Data Scientist - Algorithms & Inference,$110K-$175K,"At Nuna, our mission is to make high-quality h...",4.2,Nuna,San Francisco,San Francisco,51 to 200 employees,2010,...,110000,175000,142500.0,1,12,0,0,0,0,0
45,45,Scientist,$52K-$113K,"We are a global team of 6000 visionaries, doer...",3.4,Edgewell Personal Care,Allendale,Shelton,5001 to 10000 employees,2015,...,52000,113000,82500.0,0,7,0,0,0,1,0
46,46,Senior Data Scientist,$110K-$150K,"Working for Equity Residential (EQR), a leadin...",4.3,Equity Residential,Chicago,Chicago,1001 to 5000 employees,1993,...,110000,150000,130000.0,1,29,1,0,1,0,1
48,48,Data Scientist,Employer Provided Salary:$150K-$160KK,"BPA Services, LLC is seeking a Computer/Data S...",5.0,BPA Services,Washington,Alexandria,Unknown,-1,...,150000,160000,155000.0,0,-1,0,0,1,1,0
49,49,Lead Data Scientist,$158K-$211K,As the world's leader in digital payments tech...,3.7,Visa Inc.,Bellevue,Foster City,10000+ employees,1958,...,158000,211000,184500.0,0,64,1,0,1,0,0
50,50,Associate Data Analyst,$20K-$39K,Intrado is looking for an Associate Data Analy...,3.1,Intrado,Longmont,Omaha,5001 to 10000 employees,1986,...,20000,39000,29500.0,0,36,0,0,1,0,0
51,51,Spectral Scientist/Engineer,$56K-$117K,Thank you for your interest in joining the Cen...,4.7,Centauri,Beavercreek,Chantilly,501 to 1000 employees,1999,...,56000,117000,86500.0,0,23,0,0,0,0,0
52,52,College Hire - Data Scientist - Open to Decemb...,$63K-$99K,Description\n\nCaterpillar's legacy of industr...,3.7,Caterpillar,Peoria,Deerfield,10000+ employees,1925,...,63000,99000,81000.0,0,97,0,0,0,0,0
54,54,Data Scientist,$68K-$114K,"Overview:\n\nBlazing a new trail, we are furth...",3.8,Zimmerman Advertising,Fort Lauderdale,Fort Lauderdale,501 to 1000 employees,1984,...,68000,114000,91000.0,1,38,1,0,1,0,0
55,55,"Data Scientist, Office of Data Science",$86K-$143K,Help shape the future of Data Science across L...,3.3,Liberty Mutual Insurance,Boston,Boston,10000+ employees,1912,...,86000,143000,114500.0,1,110,1,0,0,0,0
56,56,Data Science Analyst,$41K-$95K,Torch Technologies is seeking a Junior- to MId...,4.6,"Torch Technologies, Inc.",Huntsville,Huntsville,1001 to 5000 employees,2002,...,41000,95000,68000.0,1,20,1,0,1,0,0
57,57,Data Scientist,$86K-$144K,About Swiss Re\n\nThe Swiss Re Group is one of...,3.7,Swiss Re,Armonk,Zurich,10000+ employees,1863,...,86000,144000,115000.0,0,159,1,0,1,0,0
58,58,Data Scientist,$80K-$139K,At Northrop Grumman we develop cutting-edge te...,3.7,Northrop Grumman,San Diego,Falls Church,10000+ employees,1939,...,80000,139000,109500.0,0,83,0,0,1,0,0
59,59,Data Scientist,$56K-$95K,"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius,Albuquerque,Gottingen,5001 to 10000 employees,1870,...,56000,95000,75500.0,0,152,1,0,1,0,0
60,60,Data Scientist,$120K-$189K,"About Netskope\n\nToday, there's more data and...",4.1,Netskope,San Francisco,Santa Clara,501 to 1000 employees,2012,...,120000,189000,154500.0,0,10,1,0,1,0,1
61,61,Data Scientist,$111K-$176K,About Us\n\n\nInterested in working for a huma...,4.7,1904labs,Saint Louis,Saint Louis,51 to 200 employees,2016,...,111000,176000,143500.0,1,6,1,0,0,0,1
62,62,Data Scientist,$54K-$93K,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,...,54000,93000,73500.0,1,14,0,0,1,0,0
63,63,Data Scientist,$71K-$119K,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,...,71000,119000,95000.0,1,22,1,0,1,1,0

#### Drop the 'Unnamed: 0' column in the DataFrame

In [59]:
df_modified= df_modified.drop(["Unnamed: 0"], axis=1)

In [60]:
df_modified.head(10)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,min_salary,max_salary,avg_salary,Same_Location_Hqtrs,company_age,Python,R,Excel,aws,Spark
0,Data Scientist,$53K-$91K,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,Albuquerque,Goleta,501 to 1000 employees,1973,Company - Private,...,53000,91000,72000.0,0,49,1,0,1,0,0
1,Healthcare Data Scientist,$63K-$112K,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,Linthicum,Baltimore,10000+ employees,1984,Other Organization,...,63000,112000,87500.0,0,38,1,0,0,0,0
2,Data Scientist,$80K-$90K,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,Clearwater,Clearwater,501 to 1000 employees,2010,Company - Private,...,80000,90000,85000.0,1,12,1,0,1,0,1
3,Data Scientist,$56K-$97K,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,Richland,Richland,1001 to 5000 employees,1965,Government,...,56000,97000,76500.0,1,57,1,0,0,0,0
4,Data Scientist,$86K-$143K,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,New York,51 to 200 employees,1998,Company - Private,...,86000,143000,114500.0,1,24,1,0,1,0,0
5,Data Scientist,$71K-$119K,CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne,Dallas,Dallas,201 to 500 employees,2000,Company - Public,...,71000,119000,95000.0,1,22,1,0,1,1,0
6,Data Scientist,$54K-$93K,Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage,Baltimore,Baltimore,501 to 1000 employees,2008,Company - Private,...,54000,93000,73500.0,1,14,0,0,1,0,0
7,Data Scientist,$86K-$142K,Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20,San Jose,Seattle,201 to 500 employees,2005,Company - Private,...,86000,142000,114000.0,0,17,1,0,1,1,1
8,Research Scientist,$38K-$84K,SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health,Rochester,Rochester,10000+ employees,2014,Hospital,...,38000,84000,61000.0,1,8,0,0,0,0,0
9,Data Scientist,$120K-$160K,isn’t your usual company. Our work is powered ...,4.6,<intent>,New York,New York,51 to 200 employees,2009,Company - Private,...,120000,160000,140000.0,1,13,1,0,0,0,1

#### Same the final DataFrame as 'salary_data_cleaned'

In [61]:
df_modified.to_csv("salary_data_cleaned.csv", index = False)